Repository openware/baseapp, pull requests merged in 2019-12, with the labels that each got.

#31 Fix: change check for sell order
  src/containers/Order/index.tsx
Labels: Ready

#32 Feature: CryptoIcon component added
  package.json
  src/components/CryptoIcon/CryptoIcon.pcss
  src/components/CryptoIcon/CryptoIcon.test.tsx
  src/components/CryptoIcon/__snapshots__/CryptoIcon.test.tsx.snap
  src/components/CryptoIcon/index.tsx
  src/components/CryptoIcon/readme.md
  src/components/CurrencyInfo/index.tsx
  src/components/WalletItem/index.tsx
  src/screens/WalletsScreen/WalletsScreen.pcss
Labels: Ready

#29 Feature: move pagination to components
  src/components/Pagination/Pagination.pcss
  src/components/Pagination/Pagination.test.tsx
  src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  src/components/Pagination/index.tsx
  src/components/Pagination/readme.md
  src/components/index.ts
  src/containers/HistoryElement/index.tsx
  src/containers/OrdersElement/index.tsx
  src/containers/ProfileAccountActivity/index.tsx
  src/containers/Wallets/History.tsx
Labels: Ready

#35 Feature: add bootstrap alerts
  src/containers/Alerts/Alerts.pcss
  src/containers/Alerts/index.tsx
  src/styles/colors.pcss
Labels: Ready

#39 Feature: move table from library to components
  src/components/History/History.test.tsx
  src/components/History/index.tsx
  src/components/OpenOrders/OpenOrders.test.tsx
  src/components/OpenOrders/index.tsx
  src/components/Table/Table.pcss
  src/components/Table/Table.test.tsx
  src/components/Table/index.tsx
  src/components/Table/readme.md
  src/components/index.ts
  src/containers/ProfileAccountActivity/index.tsx
  src/containers/ProfileApiKeys/index.tsx
  src/containers/RecentTrades/Market.tsx
  src/containers/RecentTrades/Yours.tsx
  src/containers/ToolBar/MarketSelector/MarketsList/index.tsx
Labels: QA: Approved

#40 Feature: move CombinedOrderBook, replace Loader with bootstrap element
  src/components/CombinedOrderBook/CombinedOrderBook.pcss
  src/components/CombinedOrderBook/CombinedOrderBook.test.tsx
  src/components/CombinedOrderBook/__snapshots__/CombinedOrderBook.test.tsx.snap
  src/components/CombinedOrderBook/index.tsx
  src/components/CombinedOrderBook/readme.md
  src/components/OrderBook/OrderBook.pcss
  src/components/OrderBook/OrderBook.test.tsx
  src/components/OrderBook/__snapshots__/OrderBook.test.tsx.snap
  src/components/OrderBook/index.tsx
  src/components/OrderBook/readme.md
  src/components/index.ts
  src/containers/Confirm/Documents/index.tsx
  src/containers/HistoryElement/index.tsx
  src/containers/Markets/index.tsx
  src/containers/OpenOrders/OpenOrders.pcss
  src/containers/OpenOrders/index.tsx
  src/containers/Order/Order.pcss
  src/containers/Order/index.tsx
  src/containers/OrderBook/OrderBook.pcss
  src/containers/OrderBook/index.tsx
  src/containers/OrdersElement/index.tsx
  src/containers/RecentTrades/RecentTrades.pcss
  src/containers/RecentTrades/Yours.tsx
  src/screens/ConfirmScreen/ConfirmScreen.pcss
  src/screens/EmailVerification/index.tsx
  src/screens/History/HistoryTab.pcss
  src/screens/OrdersTabScreen/OrdersTabScreen.pcss
  src/screens/WalletsScreen/WalletsScreen.pcss
  src/screens/WalletsScreen/index.tsx
Labels: QA: Approved, Ready

#41 Fix: resend phone confirmation if phone already exist in DB
  src/modules/user/kyc/phone/sagas/sendCodeSaga.test.ts
  src/modules/user/kyc/phone/sagas/sendCodeSaga.ts
  src/translations/en.ts
Labels: QA: Approved, Ready

#45 Feature: disable to add a beneficiary if withdraw isn't enabled to user
  .drone.yml
  src/components/Beneficiaries/Beneficiaries.pcss
  src/components/Beneficiaries/BeneficiariesFailAddModal.tsx
  src/components/Beneficiaries/index.tsx
  src/custom/translations/ru.ts
  src/modules/app.ts
  src/modules/index.ts
  src/modules/public/memberLevels/actions.test.ts
  src/modules/public/memberLevels/actions.ts
  src/modules/public/memberLevels/constants.ts
  src/modules/public/memberLevels/index.ts
  src/modules/public/memberLevels/reducer.test.ts
  src/modules/public/memberLevels/reducer.ts
  src/modules/public/memberLevels/sagas/index.ts
  src/modules/public/memberLevels/sagas/memberLevelsSaga.test.ts
  src/modules/public/memberLevels/sagas/memberLevelsSaga.ts
  src/modules/public/memberLevels/selectors.ts
  src/modules/public/memberLevels/types.ts
  src/translations/en.ts
Labels: QA: Approved, Ready

#50 Feature: improve nginx performance
  nginx.conf
Labels: Ready, YELLOW IMPRV

#42 Feature: use bootstrap checkbox instead of openware checkbox
  src/components/SignUp/SignUp.pcss
  src/components/SignUp/index.tsx
  src/containers/ProfileApiKeys/ProfileApiKeys.pcss
  src/containers/ProfileApiKeys/index.tsx
  src/containers/ProfileTwoFactorAuth/ProfileTwoFactorAuth.pcss
  src/containers/ProfileTwoFactorAuth/index.tsx
  src/containers/style.pcss
  src/screens/ProfileScreen/ProfileScreen.pcss
Labels: QA: Approved, Ready

#43 Feature: use bootstrap close button instead of openware
  src/components/OpenOrders/OpenOrders.pcss
  src/components/OpenOrders/index.tsx
  src/containers/OpenOrders/OpenOrders.pcss
  src/containers/OrdersElement/index.tsx
  src/screens/OrdersTabScreen/OrdersTabScreen.pcss
Labels: QA: Approved

#26 Feature: use bootstrap input instead of openware
  src/components/Beneficiaries/Beneficiaries.pcss
  src/components/CopyableTextField/CopyableTextField.pcss
  src/components/CopyableTextField/CopyableTextField.test.tsx
  src/components/CopyableTextField/index.tsx
  src/components/CustomInput/CustomInput.pcss
  src/components/CustomInput/index.tsx
  src/components/DepositCrypto/DepositCrypto.pcss
  src/components/DepositCrypto/DepositCrypto.test.tsx
  src/components/DepositCrypto/index.tsx
  src/components/SignIn/SignIn.pcss
  src/components/SignIn/index.tsx
  src/components/SignUp/SignUp.pcss
  src/components/SignUp/index.tsx
  src/components/style.pcss
  src/containers/ChangePassword/ChangePassword.pcss
  src/containers/ProfileApiKeys/index.tsx
  src/containers/ReferralProgram/ReferralProgram.pcss
  src/containers/TwoFactorAuth/TwoFactorAuth.pcss
  src/containers/Withdraw/index.tsx
  src/screens/ChangeForgottenPasswordScreen/index.tsx
  src/screens/ProfileScreen/ProfileScreen.pcss
  src/screens/ProfileTwoFactorAuthScreen/ProfileTwoFactorAuthScreen.pcss
  src/screens/ProfileTwoFactorAuthScreen/index.tsx
  src/screens/SignInScreen/SignInScreen.pcss
  src/screens/WalletsScreen/WalletsScreen.pcss
Labels: QA: Approved

#49 Feature: add Expired session modal
  src/assets/images/clock.svg
  src/components/ExpiredSessionModal/ExpiredSessionModal.pcss
  src/components/ExpiredSessionModal/index.tsx
  src/components/index.ts
  src/components/style.pcss
  src/custom/translations/ru.ts
  src/routes/Layout/Layout.test.tsx
  src/routes/Layout/index.tsx
  src/translations/en.ts
Labels: QA: Approved, Ready

#48 Feature: modify Trading Screen layout
  src/containers/OrderBook/OrderBook.pcss
  src/helpers/layout.ts
  src/screens/TradingScreen/index.tsx
Labels: QA: Approved, Ready
