Repository openware/baseapp, pull requests merged in 2020-12, with the labels that each got.

#334 Fix: hide close icon on header row
  src/components/OpenOrders/OpenOrders.pcss
  src/components/Table/index.tsx
Labels: Ready, Required: QA

#399 Feature: refactor process environment variables
  src/api/config.ts
  src/api/index.ts
  src/api/types.ts
  src/constants/constants.test.ts
  src/constants/index.ts
  src/helpers/jest.ts
  src/modules/public/ranger/sagas/rangerSaga.test.ts
Labels: Ready

#389 Fix: rework deposit address generation
  mocks/api/v2/barong/resource/labels/GET.mock
  mocks/api/v2/peatio/account/balances/GET.mock
  mocks/api/v2/peatio/account/balances/bch/GET.mock
  mocks/api/v2/peatio/account/balances/btc/GET.mock
  mocks/api/v2/peatio/account/balances/dash/GET.mock
  mocks/api/v2/peatio/account/balances/eth/GET.mock
  mocks/api/v2/peatio/account/balances/eur/GET.mock
  mocks/api/v2/peatio/account/balances/ltc/GET.mock
  mocks/api/v2/peatio/account/balances/usd/GET.mock
  mocks/api/v2/peatio/account/balances/xrp/GET.mock
  mocks/api/v2/peatio/account/balances/zar/GET.mock
  mocks/api/v2/peatio/account/deposit_address/bch/GET.mock
  mocks/api/v2/peatio/account/deposit_address/eth/GET.mock
  mocks/api/v2/peatio/account/deposit_address/ltc/GET.mock
  mocks/api/v2/peatio/account/deposit_address/xrp/GET.mock
  src/components/CurrencyInfo/index.tsx
  src/components/DepositCrypto/DepositCrypto.pcss
  src/components/DepositCrypto/DepositCrypto.test.tsx
  src/components/DepositCrypto/index.tsx
  src/components/WalletItem/WalletItem.test.tsx
  src/components/WalletItem/index.tsx
  src/components/WalletList/WalletList.test.tsx
  src/components/WalletList/index.tsx
  src/containers/Order/index.tsx
  src/containers/Wallets/EstimatedValue/index.tsx
  src/containers/Wallets/History.tsx
  src/custom/translations/ru.ts
  src/helpers/estimateValue.test.ts
  src/helpers/estimateValue.ts
  src/hooks/index.ts
  src/hooks/useWalletsAddressFetch.ts
  src/mobile/components/WalletDepositBody/index.tsx
  src/mobile/components/WalletWithdrawBody/index.tsx
  src/mobile/screens/WalletDeposit/index.tsx
  src/mobile/styles/components/WalletDepositBody.pcss
  src/modules/user/wallets/reducer.test.ts
  src/modules/user/wallets/reducer.ts
  src/modules/user/wallets/sagas/walletsAddressSaga.ts
  src/modules/user/wallets/sagas/walletsSaga.test.ts
  src/modules/user/wallets/sagas/walletsSaga.ts
  src/modules/user/wallets/selectors.ts
  src/modules/user/wallets/types.ts
  src/screens/WalletsScreen/WalletsScreen.pcss
  src/screens/WalletsScreen/index.tsx
  src/translations/en.ts
Labels: Ready, Required: QA, Tech: Approved
