Repository openware/baseapp, pull requests merged in 2020-07, with the labels that each got.

#182 Feature: connect sentry to the app
  .drone.yml
  Dockerfile
  package.json
  public/config/env.js
  src/api/config.ts
  src/api/types.ts
  src/containers/Errors/index.tsx
  src/custom/translations/ru.ts
  src/helpers/jest.ts
  src/index.tsx
  src/translations/en.ts
  yarn.lock
Labels: QA: Approved, Ready

#190 Fix: enable test coverage
  README.md
  jest.config.js
Labels: Ready

#183 Feature: magic link implementation
  src/assets/images/BackgroundMaintenance.tsx
  src/containers/Footer/index.tsx
  src/containers/Header/index.tsx
  src/containers/Sidebar/index.tsx
  src/custom/translations/ru.ts
  src/index.pcss
  src/modules/app.ts
  src/modules/index.ts
  src/modules/public/alert/reducer.ts
  src/modules/public/alert/sagas/handleAlertSaga.ts
  src/modules/public/blocklistAccess/actions.test.ts
  src/modules/public/blocklistAccess/actions.ts
  src/modules/public/blocklistAccess/constants.ts
  src/modules/public/blocklistAccess/index.ts
  src/modules/public/blocklistAccess/reducer.test.ts
  src/modules/public/blocklistAccess/reducer.ts
  src/modules/public/blocklistAccess/sagas/blocklistAccessFetchSaga.test.ts
  src/modules/public/blocklistAccess/sagas/blocklistAccessFetchSaga.ts
  src/modules/public/blocklistAccess/sagas/index.ts
  src/modules/public/blocklistAccess/selectors.ts
  src/modules/public/configs/sagas/configsFetchSaga.ts
  src/modules/user/profile/reducer.ts
  src/modules/user/profile/sagas/userSaga.ts
  src/routes/Layout/index.tsx
  src/screens/MagicLinkScreen/index.tsx
  src/screens/MaintenanceScreen/MaintenanceScreen.pcss
  src/screens/MaintenanceScreen/index.tsx
  src/screens/RestrictedScreen/RestrictedScreen.pcss
  src/screens/RestrictedScreen/index.tsx
  src/screens/index.ts
  src/screens/style.pcss
  src/screens/tests/MaintenanceScreen.test.tsx
  src/screens/tests/RestrictedScreen.test.tsx
  src/screens/tests/__snapshots__/MaintenanceScreen.test.tsx.snap
  src/screens/tests/__snapshots__/RestrictedScreen.test.tsx.snap
  src/translations/en.ts
Labels: QA: Approved, Ready

#199 Fix: delete redundant lang key from ForgotPassword EmailVerification
  src/screens/EmailVerification/index.tsx
  src/screens/ForgotPassword/index.tsx
Labels: QA: Approved, Ready, Tech: Approved

#195 Feature: add KYCaid support
  README.md
  public/config/env.js
  src/api/config.ts
  src/api/types.ts
  src/assets/images/kyc/CheckBigIcon.tsx
  src/assets/images/kyc/CheckIcon.tsx
  src/assets/images/kyc/ClocksIcon.tsx
  src/assets/images/kyc/CrossIcon.tsx
  src/assets/images/kyc/DocumentBackExample.svg
  src/assets/images/kyc/DocumentFrontExample.svg
  src/assets/images/kyc/DocumentSelfieExample.svg
  src/assets/images/kyc/TipIcon.tsx
  src/components/CustomInput/index.tsx
  src/components/Dropdown/index.tsx
  src/components/UploadFile/UploadFile.pcss
  src/components/UploadFile/index.tsx
  src/components/index.ts
  src/components/style.pcss
  src/constants/index.ts
  src/containers/Confirm/Address/index.tsx
  src/containers/Confirm/Documents/Documents.pcss
  src/containers/Confirm/Documents/index.tsx
  src/containers/Confirm/Identity/Identity.pcss
  src/containers/Confirm/Identity/index.tsx
  src/containers/Confirm/Phone/Phone.pcss
  src/containers/Confirm/Phone/index.tsx
  src/containers/Confirm/index.ts
  src/containers/ProfileVerification/ProfileVerification.pcss
  src/containers/ProfileVerification/index.tsx
  src/containers/index.ts
  src/containers/style.pcss
  src/custom/translations/ru.ts
  src/helpers/changeElementPosition.ts
  src/helpers/index.ts
  src/modules/app.ts
  src/modules/index.ts
  src/modules/user/kyc/addresses/actions.test.ts
  src/modules/user/kyc/addresses/actions.ts
  src/modules/user/kyc/addresses/constants.ts
  src/modules/user/kyc/addresses/index.ts
  src/modules/user/kyc/addresses/reducer.test.ts
  src/modules/user/kyc/addresses/reducer.ts
  src/modules/user/kyc/addresses/sagas/index.ts
  src/modules/user/kyc/addresses/sagas/sendAddressesSaga.test.ts
  src/modules/user/kyc/addresses/sagas/sendAddressesSaga.ts
  src/modules/user/kyc/addresses/selectors.test.ts
  src/modules/user/kyc/addresses/selectors.ts
  src/modules/user/kyc/index.ts
  src/screens/ConfirmScreen/ConfirmScreen.pcss
  src/screens/ConfirmScreen/index.tsx
  src/screens/ProfileScreen/ProfileScreen.pcss
  src/translations/en.ts
Labels: Need to QA, Ready, Tech: Approved

#192 Feature: fetch kline from finex if enabled
  src/api/config.ts
  src/api/index.ts
  src/api/requestBuilder.ts
  src/api/types.ts
  src/containers/HistoryElement/index.tsx
  src/containers/TradingChart/api.ts
  src/helpers/buildQueryString.test.ts
  src/helpers/buildQueryString.ts
  src/helpers/getTimestampPeriod.ts
  src/helpers/helpers.test.ts
  src/helpers/index.ts
  src/helpers/jest.ts
  src/helpers/uppercase.ts
  src/modules/public/kline/sagas/handleKlineFetchSaga.test.ts
  src/modules/public/kline/sagas/handleKlineFetchSaga.ts
  src/modules/public/markets/sagas/marketsFetchSaga.ts
  src/modules/public/ranger/sagas/rangerSaga.test.ts
  src/modules/public/recentTrades/sagas/recentTradesFetchSaga.ts
Labels: Need to QA, Ready

#194 Feature: withdrow amount type changed from number to string
  src/containers/Withdraw/index.tsx
  src/modules/user/wallets/reducer.test.ts
  src/modules/user/wallets/types.ts
  src/modules/user/wallets/wallets.test.ts
  src/screens/WalletsScreen/index.tsx
Labels: Need to QA, Ready, Tech: Approved

#191 Feature: update deposit address via websockets
  mocks/api/v2/peatio/account/balances/GET.mock
  mocks/api/v2/peatio/account/deposit_address/xrp/GET.mock
  mocks/ranger.js
  src/components/DepositCrypto/DepositCrypto.test.tsx
  src/components/DepositCrypto/index.tsx
  src/modules/public/ranger/helpers.test.ts
  src/modules/public/ranger/helpers.ts
  src/modules/public/ranger/sagas/rangerSaga.ts
  src/modules/user/wallets/actions.ts
  src/modules/user/wallets/constants.ts
  src/modules/user/wallets/reducer.test.ts
  src/modules/user/wallets/reducer.ts
  src/modules/user/wallets/selectors.ts
  src/screens/WalletsScreen/index.tsx
Labels: Need to QA, Ready
