Repository openware/baseapp, pull requests merged in 2020-01, with the labels that each got.

#54 Fix: use components from local directories or react-bootstrap
  src/components/CombinedOrderBook/CombinedOrderBook.test.tsx
  src/components/CombinedOrderBook/index.tsx
  src/components/OrderBook/OrderBook.test.tsx
  src/components/OrderBook/index.tsx
  src/containers/ChangePassword/index.tsx
  src/containers/ToolBar/MarketSelector/MarketsTabs/index.tsx
  src/screens/ProfileTwoFactorAuthScreen/index.tsx
Labels: Ready

#52 Feature: increase app performance
  config-overrides.js
  package.json
  public/index.html
  robots.txt
  src/assets/fonts/Montserrat-Bold.ttf
  src/assets/fonts/Montserrat-Regular.ttf
  src/assets/fonts/Roboto-Medium.ttf
  src/assets/fonts/Roboto-Regular.ttf
  src/assets/fonts/Roboto-Thin.ttf
  src/styles/fonts.pcss
  src/styles/style.pcss
  yarn.lock
Labels: Ready

#53 Fix: replace Loader fronm lib with bootstrap one
  src/routes/Layout/index.tsx
Labels: Needs: QA, Ready

#57 Fix: remove ability to resize Trading items
  src/components/Grid/Grid.pcss
  src/helpers/layout.ts
  src/index.pcss
Labels: Needs: QA, Ready

#55 Feature: Markets, Marketdepth, Orderinput and PercantageButton compon…
  src/components/CustomInput/index.tsx
  src/components/MarketDepths/MarketDepths.pcss
  src/components/MarketDepths/MarketDepths.test.tsx
  src/components/MarketDepths/__snapshots__/MarketDepths.test.tsx.snap
  src/components/MarketDepths/index.tsx
  src/components/MarketDepths/readme.md
  src/components/Markets/Markets.pcss
  src/components/Markets/Markets.test.tsx
  src/components/Markets/__snapshots__/Markets.test.tsx.snap
  src/components/Markets/index.tsx
  src/components/Markets/readme.md
  src/components/OrderForm/OrderForm.pcss
  src/components/OrderForm/OrderForm.test.tsx
  src/components/OrderForm/index.tsx
  src/components/OrderInput/OrderInput.pcss
  src/components/OrderInput/OrderInput.test.tsx
  src/components/OrderInput/__snapshots__/OrderInput.test.tsx.snap
  src/components/OrderInput/index.tsx
  src/components/OrderInput/readme.md
  src/components/PercentageButton/PercentageButton.pcss
  src/components/PercentageButton/PercentageButton.test.tsx
  src/components/PercentageButton/__snapshots__/PercentageButton.test.tsx.snap
  src/components/PercentageButton/index.tsx
  src/components/PercentageButton/readme.md
  src/components/index.ts
  src/components/style.pcss
  src/containers/MarketDepth/index.tsx
  src/containers/Markets/index.tsx
Labels: Ready

#65 Fix: change market depth data type
  src/containers/MarketDepth/index.tsx
Labels: Ready

#67 Fix: change kyc styles
  src/components/Dropdown/Dropdown.pcss
  src/containers/Confirm/Phone/Phone.pcss
Labels: Ready

#61 Feature: add geetest captcha
  package.json
  src/components/SignUp/SignUp.test.tsx
  src/components/SignUp/index.tsx
  src/containers/GeetestCaptcha/index.tsx
  src/containers/index.ts
  src/helpers/geetest.js
  src/helpers/index.ts
  src/modules/app.ts
  src/modules/index.ts
  src/modules/user/auth/actions.test.ts
  src/modules/user/auth/actions.ts
  src/modules/user/auth/constants.ts
  src/modules/user/auth/reducer.test.ts
  src/modules/user/auth/reducer.ts
  src/modules/user/auth/selectors.ts
  src/modules/user/captcha/actions.ts
  src/modules/user/captcha/constants.ts
  src/modules/user/captcha/index.ts
  src/modules/user/captcha/reducer.ts
  src/modules/user/captcha/sagas/geetestCaptchaSaga.ts
  src/modules/user/captcha/sagas/index.ts
  src/modules/user/captcha/selectors.ts
  src/screens/SignUpScreen/index.tsx
Labels: QA: Approved, Ready

#69 Fix: components style polish
  src/components/Dropdown/Dropdown.pcss
  src/components/OrderInput/OrderInput.pcss
  src/components/OrderInput/index.tsx
  src/components/SignUp/SignUp.pcss
  src/containers/ChangePassword/ChangePassword.pcss
  src/containers/Confirm/Documents/Documents.pcss
  src/containers/Confirm/Documents/index.tsx
  src/containers/Confirm/Identity/Identity.pcss
  src/containers/Confirm/Identity/index.tsx
  src/containers/Confirm/Phone/index.tsx
  src/containers/ProfileApiKeys/index.tsx
  src/containers/ProfileAuthDetails/index.tsx
  src/helpers/layout.ts
Labels: Needs: QA, Ready

#72 Fix/elements style polish
  src/components/CustomInput/CustomInput.pcss
  src/components/OrderInput/OrderInput.pcss
  src/containers/Confirm/Documents/index.tsx
  src/containers/Order/Order.pcss
  src/custom/translations/ru.ts
  src/screens/ProfileScreen/ProfileScreen.pcss
  src/screens/ProfileTwoFactorAuthScreen/ProfileTwoFactorAuthScreen.pcss
  src/screens/WalletsScreen/WalletsScreen.pcss
  src/translations/en.ts
Labels: QA: Approved, Ready

#76 Fix: remove async loading of env js
  public/index.html
Labels: QA: Approved, Ready

#77 Fix: Deposit copyable field border on click
  src/components/DepositCrypto/DepositCrypto.pcss
Labels: QA: Approved, Ready

#73 Fix: isResizable and isDraggable are optional arguments
  public/config/env.js
  src/api/config.ts
  src/api/types.ts
  src/components/FilterInput/FilterInput.pcss
  src/components/Grid/Grid.pcss
  src/helpers/jest.ts
  src/helpers/layout.ts
Labels: QA: Approved, Ready

#81 Fix: use new structure of trade at yours tab
  src/containers/RecentTrades/Yours.tsx
  src/modules/public/ranger/sagas/rangerSaga.test.ts
  src/modules/user/history/sagas/historyPushSaga.ts
  src/modules/user/history/types.ts
Labels: QA: Approved

#79 Feature: add Google Analytics with gaTrackerKey in env.js
  src/routes/Layout/index.tsx
Labels: Ready

#70 Feature: add configs by api
  .drone.yml
  README.md
  mocks/api/v2/barong/identity/configs/GET.mock
  public/config/env.js
  src/api/config.ts
  src/api/types.ts
  src/helpers/jest.ts
  src/modules/app.ts
  src/modules/index.ts
  src/modules/public/configs/actions.test.ts
  src/modules/public/configs/actions.ts
  src/modules/public/configs/constants.ts
  src/modules/public/configs/index.ts
  src/modules/public/configs/reducer.test.ts
  src/modules/public/configs/reducer.ts
  src/modules/public/configs/sagas/configsFetchSaga.test.ts
  src/modules/public/configs/sagas/configsFetchSaga.ts
  src/modules/public/configs/sagas/index.ts
  src/modules/public/configs/selectors.ts
  src/modules/public/configs/types.ts
  src/routes/Layout/index.tsx
  src/screens/SignUpScreen/index.tsx
Labels: QA: Approved, Ready

#86 Fix: prevent double rendering with GA-Tracker usage
  src/App.tsx
  src/helpers/gaTracker.tsx
  src/index.tsx
  src/routes/Layout/index.tsx
Labels: QA: Approved, Ready
