Repository openware/baseapp, pull requests merged in 2020-05, with the labels that each got.

#154 Fix: change withdrawal total formatting
  src/containers/ModalWithdrawConfirmation/index.tsx
  src/containers/Withdraw/index.tsx
  src/modules/user/wallets/reducer.test.ts
  src/modules/user/wallets/types.ts
  src/modules/user/wallets/wallets.test.ts
  src/screens/WalletsScreen/index.tsx
Labels: QA: Approved, Ready

#165 Fix: change total precising method
  src/components/OrderForm/index.tsx
Labels: Need to QA, Ready

#166 Fix: push new order to the top of list
  src/modules/user/openOrders/helpers.ts
Labels: Ready

#164 Fix: trigger last price update on ticker and open orders change
  src/containers/OrderBook/index.tsx
Labels: Optimization, QA: Approved, Ready

#155 Fix: add total calculation empty ob case
  src/components/Order/index.tsx
  src/helpers/getTotalPrice.ts
  src/helpers/helpers.test.ts
Labels: QA: Approved, Ready

#176 Fix: remove customization settings fetch
  src/routes/Layout/index.tsx
Labels: Ready

#159 Feature: add alert on order push by ws
  mocks/ranger.js
  src/modules/public/ranger/sagas/rangerSaga.ts
  src/modules/user/orders/sagas/ordersExecuteSaga.ts
Labels: QA: Approved, Ready

#68 Fix: change volume precision to display
  src/containers/HeaderToolbar/index.tsx
  src/containers/ToolBar/MarketSelector/MarketsList/index.tsx
Labels: QA: Approved, Tech: Approved
