Repository openware/baseapp, pull requests merged in 2020-04, with the labels that each got.

#130 Fix: remove total header for histories, rework pagination logic
  src/containers/HistoryElement/index.tsx
  src/containers/OrdersElement/index.tsx
  src/containers/Wallets/History.tsx
  src/modules/user/history/actions.test.ts
  src/modules/user/history/actions.ts
  src/modules/user/history/reducer.ts
  src/modules/user/history/sagas/historySaga.test.ts
  src/modules/user/history/sagas/historySaga.ts
  src/modules/user/history/selectors.ts
  src/modules/user/ordersHistory/actions.test.ts
  src/modules/user/ordersHistory/actions.ts
  src/modules/user/ordersHistory/reducer.test.ts
  src/modules/user/ordersHistory/reducer.ts
  src/modules/user/ordersHistory/sagas/ordersHistorySaga.test.ts
  src/modules/user/ordersHistory/sagas/ordersHistorySaga.ts
  src/modules/user/ordersHistory/selectors.ts
Labels: Ready

#128 Feature: add ability to cancel all finex orders
  src/containers/OpenOrders/index.tsx
  src/modules/user/ordersHistory/actions.test.ts
  src/modules/user/ordersHistory/actions.ts
  src/modules/user/ordersHistory/reducer.test.ts
  src/modules/user/ordersHistory/sagas/ordersCancelAllSaga.test.ts
  src/screens/OrdersTabScreen/index.tsx
Labels: 2.4, Need to QA, Ready, Tech: Approved

#142 Fix: search input of Market selector
  src/containers/ToolBar/MarketSelector/MarketsList/index.tsx
Labels: Ready

#144 Fix: Update react-grid-layout to use React.memo for children
  package.json
  src/components/Grid/Grid.pcss
  src/components/Grid/Grid.test.tsx
  src/components/Grid/__snapshots__/Grid.test.tsx.snap
  src/components/Grid/index.tsx
  src/components/GridItem/index.tsx
  src/components/index.ts
  src/components/style.pcss
  src/helpers/layout.ts
  src/modules/public/gridLayout/actions.test.ts
  src/modules/public/gridLayout/actions.ts
  src/modules/public/gridLayout/reducer.test.ts
  src/modules/public/gridLayout/reducer.ts
  src/screens/TradingScreen/index.tsx
  yarn.lock
Labels: WIP

#146 Fix: change alert layer
  src/containers/Alerts/Alerts.pcss
Labels: Ready

#150 Feature: intl message storing refactoring
  src/App.tsx
  src/modules/public/i18n/reducer.test.ts
  src/modules/public/i18n/reducer.ts
Labels: Ready

#149 Fix: prevent memory leaks of modules
  src/helpers/index.ts
  src/helpers/sliceArray.ts
  src/modules/public/orderBook/reducer.ts
  src/modules/public/ranger/reducer.ts
  src/modules/public/recentTrades/reducer.ts
  src/modules/user/history/reducer.ts
  src/modules/user/history/sagas/historyPushSaga.ts
  src/modules/user/history/sagas/historySaga.ts
  src/modules/user/newHistory/reducer.ts
  src/modules/user/openOrders/reducer.ts
  src/modules/user/ordersHistory/reducer.ts
  src/modules/user/userActivity/reducer.ts
Labels: Ready

#151 Fix: move wallets fetch to container
  src/containers/Markets/index.tsx
  src/containers/Order/index.tsx
  src/screens/TradingScreen/index.tsx
Labels: Ready

#153 Fix: solve minor styles issues
  src/components/Dropdown/Dropdown.pcss
  src/containers/NavBar/NavBar.pcss
  src/containers/Sidebar/Sidebar.pcss
Labels: Ready, Tech: Approved

#162 Fix: display Beneficiary name instead of address in list
  src/components/Beneficiaries/index.tsx
  src/custom/translations/ru.ts
  src/translations/en.ts
Labels: Ready, Tech: Approved
