Repository openware/baseapp, pull requests merged in 2020-09, with the labels that each got.

#298 Feature: Move RecentTrades to func component
  src/containers/RecentTrades/RecentTrades.test.tsx
  src/containers/RecentTrades/index.tsx
Labels: Optimization

#268 Fix: remove country from address verification
  src/containers/Confirm/Address/index.tsx
  src/custom/translations/ru.ts
  src/translations/en.ts
Labels: Need to QA, Ready, Tech: Approved

#171 Feature: add finex price filters
  mocks/api/v2/finex/public/markets/GET.mock
  public/config/env.js
  src/components/Order/Order.test.tsx
  src/components/Order/index.tsx
  src/components/OrderForm/OrderForm.pcss
  src/components/OrderForm/OrderForm.test.tsx
  src/components/OrderForm/index.tsx
  src/components/OrderInput/OrderInput.pcss
  src/components/OrderInput/index.tsx
  src/containers/Order/Order.pcss
  src/containers/Order/index.tsx
  src/custom/translations/ru.ts
  src/filters/FilterPrice/FilterPriceCustomStep.ts
  src/filters/FilterPrice/FilterPriceSignificantDigit.ts
  src/filters/FilterPrice/index.test.ts
  src/filters/FilterPrice/index.ts
  src/filters/index.ts
  src/helpers/index.ts
  src/mobile/styles/components/CreateOrder.pcss
  src/modules/public/markets/reducer.ts
  src/modules/public/markets/sagas/marketsFetchSaga.ts
  src/modules/public/markets/selectors.ts
  src/modules/public/markets/types.ts
  src/translations/en.ts
Labels: 2.6, Need to QA, Ready, Tech: Approved

#287 Feature: hide documents image uploading fields before ID type selected
  src/containers/Confirm/Documents/index.tsx
Labels: 2.5, 2.6, Need to QA, Ready

#297 Feature: add order input action buttons
  src/components/Order/index.tsx
  src/components/OrderForm/OrderForm.pcss
  src/components/OrderForm/index.tsx
  src/containers/Order/index.tsx
  src/filters/FilterPrice/index.test.ts
  src/filters/FilterPrice/index.ts
  src/mobile/assets/images/MinusIcon.tsx
  src/mobile/assets/images/PlusIcon.tsx
  src/mobile/components/OrderInput/index.tsx
  src/mobile/components/index.ts
  src/mobile/styles/components/CreateOrder.pcss
  src/mobile/styles/components/OrderInput.pcss
  src/mobile/styles/components/styles.pcss
  src/mobile/translations/en.ts
Labels: 2.6, Mobile, QA: Approved, Ready

#302 Fix: clear user data from alert error
  src/modules/public/alert/sagas/handleAlertSaga.ts
  src/modules/public/alert/sagas/handleErrorAlert.test.ts
Labels: Mobile, QA: Approved, Ready

#303 Fix: change ob styles and depth fetch hook
  src/containers/OrderBook/OrderBook.pcss
  src/hooks/useDepthFetch.ts
  src/modules/public/orderBook/selectors.ts
Labels: Mobile, Ready

#308 Fix: change KYC upload image styles
  src/components/UploadFile/UploadFile.pcss
  src/mobile/styles/screens/ConfirmMobileScreen.pcss
Labels: Ready

#295 Fix: add missing thousand separators
  src/components/CurrencyInfo/index.tsx
  src/components/Decimal/index.tsx
  src/components/OrderForm/index.tsx
  src/components/WalletItem/index.tsx
  src/containers/HeaderToolbar/index.tsx
  src/containers/HistoryElement/index.tsx
  src/containers/Markets/index.tsx
  src/containers/ModalWithdrawConfirmation/index.tsx
  src/containers/OpenOrders/index.tsx
  src/containers/Order/index.tsx
  src/containers/OrderBook/index.tsx
  src/containers/OrdersElement/index.tsx
  src/containers/RecentTrades/Market.tsx
  src/containers/RecentTrades/Yours.tsx
  src/containers/ToolBar/MarketSelector/MarketsList/index.tsx
  src/containers/Wallets/EstimatedValue/index.tsx
  src/containers/Wallets/History.tsx
  src/containers/Withdraw/index.tsx
  src/helpers/helpers.test.ts
  src/helpers/index.ts
  src/helpers/preciseNumber.ts
  src/screens/TradingScreen/index.tsx
  src/screens/WalletsScreen/index.tsx
Labels: 2.6, Ready, Tech: Approved

#321 Fix: add check for user loadding for preventing user redirection after page refreshing
  src/routes/Layout/index.tsx
Labels: Ready

#315 Fix: display pending beneficiary status
  src/components/Beneficiaries/index.tsx
  src/mobile/styles/components/WalletWithdrawBody.pcss
Labels: Ready

#313 Fix: add ability to return from confirm page
  src/assets/images/kyc/CrossIcon.tsx
  src/mobile/styles/screens/ConfirmMobileScreen.pcss
  src/screens/ConfirmScreen/ConfirmScreen.pcss
  src/screens/ConfirmScreen/index.tsx
Labels: Ready

#310 Fix: add address middle truncation
  src/containers/HistoryElement/index.tsx
  src/helpers/helpers.test.ts
  src/helpers/index.ts
  src/helpers/truncateMiddle.ts
Labels: Ready

#312 Fix: change markets component paddings
  src/components/FilterInput/FilterInput.pcss
  src/components/Markets/Markets.pcss
  src/components/OpenOrders/OpenOrders.pcss
  src/components/Table/Table.pcss
  src/index.pcss
Labels: Ready

#311 Fix: change beneficiary focused field to first
  src/components/Beneficiaries/BeneficiariesAddModal.tsx
Labels: Ready, Tech: Approved

#322 Feature: Strong password component for Change Password
  src/components/ChangePassword/ChangePassword.pcss
  src/components/ChangePassword/index.tsx
  src/components/index.ts
  src/components/style.pcss
  src/containers/ProfileAuthDetails/index.tsx
  src/mobile/components/ChangePassword/index.tsx
  src/mobile/components/index.ts
  src/mobile/screens/ProfileChangePassword/index.tsx
  src/mobile/styles/components/styles.pcss
  src/screens/ChangeForgottenPasswordScreen/index.tsx
Labels: Ready

#323 Fix: add ability to control dragging and resizing of components
  src/index.pcss
Labels: Ready

#300 Feature: Refactor recent trades child
  src/components/Markets/Markets.test.tsx
  src/components/OrderBook/OrderBook.test.tsx
  src/components/Table/Table.pcss
  src/components/Table/Table.test.tsx
  src/components/Table/index.tsx
  src/constants/index.ts
  src/containers/RecentTrades/Market.tsx
  src/containers/RecentTrades/RecentTradesTableCell.tsx
  src/containers/RecentTrades/Yours.tsx
  src/containers/Wallets/History.tsx
  src/mobile/components/HistoryTable/index.tsx
Labels: Ready, Tech: Approved

#306 Feature: Move order book to func component
  src/containers/OrderBook/OrderBookTableRow.tsx
  src/containers/OrderBook/index.tsx
Labels: Ready, Tech: Approved

#304 Feature: Refactor markets
  src/components/FilterInput/index.tsx
  src/components/Markets/Markets.test.tsx
  src/components/Markets/index.tsx
  src/components/Table/Table.test.tsx
  src/constants/index.ts
  src/containers/Markets/index.tsx
  src/helpers/hasDuplicates.ts
  src/helpers/helpers.test.ts
  src/helpers/index.ts
Labels: Ready, Tech: Approved

#104 Fix: kyc forms autofill
  src/components/CustomInput/index.tsx
  src/containers/Confirm/Identity/index.tsx
  src/containers/Confirm/Phone/index.tsx
  src/screens/ConfirmScreen/ConfirmScreen.pcss
Labels: QA: Approved, Tech: Approved

#327 Fix: add country dropdown to address confirm step
  src/containers/Confirm/Address/index.tsx
  src/screens/ConfirmScreen/ConfirmScreen.pcss
Labels: Need to QA

#319 Feature: Move order form to func component
  src/components/Dropdown/Dropdown.test.tsx
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/components/Dropdown/index.tsx
  src/components/Order/Order.test.tsx
  src/components/Order/__snapshots__/Order.test.tsx.snap
  src/components/Order/index.tsx
  src/components/OrderForm/OrderForm.test.tsx
  src/components/OrderForm/__snapshots__/OrderForm.test.tsx.snap
  src/components/OrderForm/index.tsx
  src/components/OrderInput/index.tsx
  src/constants/index.ts
  src/containers/Order/index.tsx
  src/helpers/convertToString.ts
  src/helpers/index.ts
Labels: Ready
