Repository openware/baseapp, pull requests merged in 2020-02, with the labels that each got.

#92 Fix: bug fix from v2.3
  src/containers/OrderBook/OrderBook.pcss
  src/custom/translations/ru.ts
  src/helpers/helpers.test.ts
  src/helpers/historyTableUtils.ts
  src/translations/en.ts
Labels: QA: Approved, Ready

#87 Feature: configure languages from env.js
  public/config/env.js
  src/api/config.ts
  src/api/types.ts
  src/containers/Confirm/Identity/index.tsx
  src/containers/Sidebar/index.tsx
  src/containers/TradingChart/index.tsx
  src/helpers/jest.ts
Labels: QA: Approved, Ready

#94 Feature: total decimal equal to base and quote units decimal
  src/components/OrderForm/OrderForm.test.tsx
  src/components/OrderForm/index.tsx
Labels: Tech: Approved

#106 Feature: add landing page
  src/App.tsx
  src/assets/images/landing/GridMainBG.svg
  src/assets/images/landing/GridSecondBG.svg
  src/assets/images/landing/PhoneImage.svg
  src/assets/images/landing/TradingUIFullBG.png
  src/assets/images/landing/features/API.svg
  src/assets/images/landing/features/Community.svg
  src/assets/images/landing/features/Customize.svg
  src/assets/images/landing/features/Exchange.svg
  src/assets/images/landing/features/Security.svg
  src/assets/images/landing/features/Types.svg
  src/assets/images/landing/social/CoinMarket.svg
  src/assets/images/landing/social/Facebook.svg
  src/assets/images/landing/social/LinkedIn.svg
  src/assets/images/landing/social/Medium.svg
  src/assets/images/landing/social/Reddit.svg
  src/assets/images/landing/social/Telegram.svg
  src/assets/images/landing/social/Twitter.svg
  src/assets/images/landing/social/YouTube.svg
  src/components/TickerTable/TickerTable.pcss
  src/components/TickerTable/index.tsx
  src/components/index.ts
  src/components/style.pcss
  src/containers/Header/Header.pcss
  src/containers/Header/index.tsx
  src/containers/MarketsTable/index.tsx
  src/containers/index.ts
  src/custom/translations/ru.ts
  src/routes/Layout/index.tsx
  src/screens/LandingScreen/LandingScreen.pcss
  src/screens/LandingScreen/index.tsx
  src/screens/index.ts
  src/screens/style.pcss
  src/styles/themes/basic.pcss
  src/styles/themes/light.pcss
  src/translations/en.ts
Labels: Ready

#100 Feature: add finex option to env.js
  public/config/env.js
  src/api/config.ts
  src/api/index.ts
  src/api/requestBuilder.ts
  src/api/types.ts
  src/containers/OpenOrders/index.tsx
  src/helpers/getOrderAPI.ts
  src/helpers/index.ts
  src/helpers/jest.ts
  src/modules/public/ranger/sagas/rangerSaga.test.ts
  src/modules/user/openOrders/sagas/openOrdersCancelSaga.ts
  src/modules/user/openOrders/sagas/userOpenOrdersFetchSaga.ts
  src/modules/user/orders/orders.test.ts
  src/modules/user/orders/sagas/ordersExecuteSaga.ts
  src/modules/user/ordersHistory/sagas/ordersCancelAllSaga.ts
Labels: Ready

#99 Feature: generate deposit address
  src/components/CurrencyInfo/index.tsx
  src/components/DepositCrypto/DepositCrypto.pcss
  src/components/DepositCrypto/DepositCrypto.test.tsx
  src/components/DepositCrypto/index.tsx
  src/components/WalletItem/WalletItem.test.tsx
  src/components/WalletItem/index.tsx
  src/components/WalletList/WalletList.test.tsx
  src/containers/Order/index.tsx
  src/custom/translations/ru.ts
  src/helpers/estimateValue.ts
  src/modules/user/wallets/reducer.test.ts
  src/modules/user/wallets/sagas/walletsSaga.test.ts
  src/modules/user/wallets/sagas/walletsSaga.ts
  src/modules/user/wallets/types.ts
  src/screens/WalletsScreen/index.tsx
  src/translations/en.ts
Labels: QA: Approved, Ready
