Repository openware/baseapp, pull requests merged in 2020-10, with the labels that each got.

#331 Fix: remove scroll from disable deposit screen
  src/mobile/styles/components/WalletDepositBody.pcss
Labels: Mobile, Ready, Tech: Approved

#335 Fix: fit content at recent trades component
  src/containers/RecentTrades/RecentTrades.pcss
Labels: Ready

#336 Fix: change market selector width
  src/containers/ToolBar/MarketSelector/MarketSelector.pcss
  src/containers/ToolBar/MarketSelector/MarketsTabs/MarketsTabs.pcss
Labels: Ready

#338 Fix: clean price and amount inputs, if market was changed. Price fiel…
  src/components/OrderForm/index.tsx
  src/components/OrderInput/OrderInput.pcss
  src/containers/Order/Order.pcss
Labels: Ready

#342 Rename mock: take into account nested objects
  mocks/api/v2/peatio/account/beneficiaries/POST--currency=btc&name=111&data.address=111.mock
Labels: Ready

#339 Fix: remove reset history during change tab
  src/containers/RecentTrades/index.tsx
Labels: Ready

#347 Fix: rerender orderbook after resize
  src/containers/OrderBook/index.tsx
Labels: Ready

#346 Fix: display full referral link
  src/containers/ReferralProgram/ReferralProgram.pcss
Labels: Ready

#345 Fix: mobile orderbook polish
  src/mobile/styles/components/CreateOrder.pcss
Labels: Ready

#328 Fix: display alert about taken email
  src/modules/public/alert/sagas/handleAlertSaga.ts
Labels: Ready, Tech: Approved

#351 Fix: update .domains file
  .domains
Labels: 2.5, Ready

#353 Fix: remove generate address button, update fetch address logic
  package.json
  src/components/DepositCrypto/DepositCrypto.test.tsx
  src/components/DepositCrypto/index.tsx
  src/mobile/components/WalletDepositBody/index.tsx
  src/modules/user/beneficiaries/actions.ts
  src/screens/WalletsScreen/index.tsx
  yarn.lock
Labels: Ready

#348 Fix: change landing text colors
  src/screens/LandingScreen/index.tsx
Labels: Ready

#337 Fix: don't show alert for invalid session, if user doesn't logged in
  src/modules/public/alert/sagas/handleAlertSaga.ts
Labels: Ready

#329 Fix: fetch email from user interface at email verification screen
  src/screens/EmailVerification/index.tsx
  src/screens/SignInScreen/index.tsx
Labels: Ready, Required: QA, Tech: Approved

#355 Feature: Refactor beneficiaries
  src/components/Beneficiaries/BeneficiariesActivateModal.tsx
  src/components/Beneficiaries/BeneficiariesAddModal.tsx
  src/components/Beneficiaries/BeneficiariesFailAddModal.tsx
  src/components/Beneficiaries/index.tsx
Labels: QA: Approved, Ready

#341 fix for windows: handle props on child objects
  mocks/mockserver.js
Labels: Ready, Tech: Approved

#349 Fix: prevent grid elements overlay
  src/screens/TradingScreen/index.tsx
Labels: QA: Approved, Ready, Tech: Approved

#362 Fix: handle multiple currencies in the deposit address payload
  mocks/api/v2/peatio/account/deposit_address/bch/GET.mock
  mocks/api/v2/peatio/account/deposit_address/btc/GET.mock
  mocks/api/v2/peatio/account/deposit_address/dash/GET.mock
  mocks/api/v2/peatio/account/deposit_address/eth/GET.mock
  mocks/api/v2/peatio/account/deposit_address/ltc/GET.mock
  mocks/api/v2/peatio/account/deposit_address/xrp/GET.mock
  mocks/ranger.js
  src/modules/user/wallets/reducer.test.ts
  src/modules/user/wallets/reducer.ts
  src/modules/user/wallets/sagas/walletsAddressSaga.ts
  src/modules/user/wallets/types.ts
Labels: Ready

#350 Fix: filter zero amount asks and bids
  src/helpers/handleIncrementalUpdate.ts
Labels: Ready

#330 Feature: Withdraw Confirmation mobile modal
  src/mobile/components/ModalWithdrawConfirmation/index.tsx
  src/mobile/components/WalletWithdrawBody/index.tsx
  src/mobile/components/index.ts
  src/mobile/styles/components/Modal.pcss
  src/mobile/styles/components/ModalWithdrawConfirmation.pcss
  src/mobile/styles/components/WalletWithdrawBody.pcss
  src/mobile/styles/components/styles.pcss
  src/mobile/translations/en.ts
  yarn.lock
Labels: Mobile, Ready

#363 fix prettier
  .prettierrc
  package.json
  src/components/EmailForm/index.tsx
  src/components/SignUp/index.tsx
  src/components/Tooltip/index.tsx
  src/screens/ProfileTwoFactorAuthScreen/index.tsx
  tsconfig.prod.json
  tslint.json
  yarn.lock
Labels: Ready

#354 Feature: Move some components to functional components
  src/components/Dropdown/Dropdown.test.tsx
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/components/Dropdown/index.tsx
  src/components/FilterInput/index.tsx
  src/components/Markets/Markets.test.tsx
  src/components/Markets/__snapshots__/Markets.test.tsx.snap
  src/components/Markets/index.tsx
  src/components/Table/Table.pcss
  src/components/Table/index.tsx
  src/constants/index.ts
  src/containers/Markets/index.tsx
  src/containers/RecentTrades/Yours.tsx
  src/containers/Wallets/History.tsx
  src/helpers/convertToString.ts
  src/helpers/hasDuplicates.ts
  src/helpers/helpers.test.ts
  src/helpers/index.ts
  src/hooks/index.ts
  src/hooks/redux.ts
  src/mobile/components/HistoryTable/index.tsx
  tslint.json
Labels: Ready

#367 Fix: prevent light mode on landing screen
  src/screens/LandingScreen/index.tsx
Labels: Required: QA, Tech: Approved

#370 Feature: add integration with MetaMask
  package.json
  src/assets/images/MetaMaskLogo.tsx
  src/components/DepositCrypto/DepositCrypto.pcss
  src/components/DepositCrypto/DepositCrypto.test.tsx
  src/components/DepositCrypto/index.tsx
  src/components/MetaMaskButton/MetaMaskButton.pcss
  src/components/MetaMaskButton/index.tsx
  src/components/index.ts
  src/components/style.pcss
  src/custom/translations/ru.ts
  src/helpers/index.ts
  src/helpers/providers.tsx
  src/mobile/components/WalletDepositBody/index.tsx
  src/modules/public/errorHandler/helpers/getMetaMaskErrorMessage.ts
  src/modules/public/errorHandler/sagas/handleErrorSaga.ts
  src/screens/WalletsScreen/index.tsx
  src/translations/en.ts
  yarn.lock
Labels: Ready, Required: QA, Tech: Approved

#371 Fix: handle beneficiaries errors
  src/components/Beneficiaries/Beneficiaries.pcss
  src/components/Beneficiaries/BeneficiariesActivateModal.tsx
  src/custom/translations/ru.ts
  src/translations/en.ts
Labels: Ready

#343 Feature: Refactor components
  src/components/PasswordStrengthMeter/index.tsx
  src/components/PasswordStrengthTip/index.tsx
  src/components/PercentageButton/index.tsx
  src/components/QRCode/index.tsx
  src/components/SignIn/index.tsx
  src/components/SignUp/index.tsx
  src/components/SummaryField/index.tsx
  src/components/TabPanel/index.tsx
  src/components/TickerTable/index.tsx
  src/components/Tooltip/index.tsx
  src/components/TwoFactorAuth/index.tsx
  src/components/UploadFile/index.tsx
  src/components/WalletItem/index.tsx
  src/components/WalletList/index.tsx
  src/containers/ProfileVerification/index.tsx
  tslint.json
Labels: Ready
