Repository openware/baseapp, pull requests merged in 2021-02, with the labels that each got.

#446 Fix: adjust modal spacing using padding, not absolute position
  src/components/Beneficiaries/Beneficiaries.pcss
  src/components/EmailForm/EmailForm.pcss
  src/mobile/styles/components/Modal.pcss
  src/mobile/styles/components/WalletWithdrawBody.pcss
Labels: Ready

#450 Fix: 2FA app store link
  src/screens/ProfileTwoFactorAuthScreen/index.tsx
  src/screens/tests/__snapshots__/ProfileTwoFactorAuthScreen.test.tsx.snap
Labels: Ready

#453 Fix: deposit translations, 2fa form height
  mocks/api/v2/peatio/account/deposits/GET--page=1&limit=25.mock
  src/components/Markets/__snapshots__/Markets.test.tsx.snap
  src/containers/TwoFactorAuth/TwoFactorAuth.pcss
  src/custom/translations/ru.ts
  src/mobile/components/HistoryTable/index.tsx
  src/translations/en.ts
Labels: 2.6, Ready

#454 Fix: deposit translations, 2fa form height (#453)
  mocks/api/v2/peatio/account/deposits/GET--page=1&limit=25.mock
  src/containers/TwoFactorAuth/TwoFactorAuth.pcss
  src/custom/translations/ru.ts
  src/mobile/components/HistoryTable/index.tsx
  src/translations/en.ts
Labels: 2.6

#456 Fix: change customization menu styles
  src/components/Customization/Themes/ColorSettings/ColorSettings.pcss
  src/components/Customization/Themes/Themes.pcss
Labels: Ready

#457 Fix: decrease required height for mobile mode
  src/hooks/useSetMobileDevice.ts
Labels: Ready

#423 Fix: add list of acceptable documents types to upload
  mocks/api/v2/peatio/account/beneficiaries/10/DELETE.mock
  mocks/api/v2/peatio/account/beneficiaries/10/OPTIONS.mock
  src/components/UploadFile/index.tsx
Labels: 2.6, Ready

#463 Fix: change quotes to solve linter warning
  src/components/UploadFile/index.tsx
Labels: Ready

#464 Feature: add synchronous config fetch from sonic
  .drone.yml
  .gitignore
  README.md
  mocks/api/v2/sonic/public/config/GET.mock
  public/config.js
  public/config/env.js
  src/app/template.html
Labels: Ready

#469 Feature: fetch and update platform configs from sonic
  mocks/api/v2/admin/baseapp/secret/OPTIONS.mock
  mocks/api/v2/admin/baseapp/secret/PUT.mock
  mocks/api/v2/public/config/GET.mock
  public/config.js
  src/api/config.ts
  src/api/index.ts
  src/api/requestBuilder.ts
  src/api/types.ts
  src/components/Captcha/index.tsx
  src/components/ChangePassword/index.tsx
  src/components/SignUp/index.tsx
  src/containers/Footer/index.tsx
  src/containers/Header/index.tsx
  src/containers/ProfileAuthDetails/index.tsx
  src/mobile/screens/ProfileChangePassword/index.tsx
  src/modules/app.ts
  src/modules/index.ts
  src/modules/public/blocklistAccess/reducer.test.ts
  src/modules/public/blocklistAccess/reducer.ts
  src/modules/public/configs/actions.test.ts
  src/modules/public/configs/actions.ts
  src/modules/public/configs/constants.ts
  src/modules/public/configs/reducer.test.ts
  src/modules/public/configs/reducer.ts
  src/modules/public/configs/sagas/configsFetchSaga.ts
  src/modules/public/configs/sagas/index.ts
  src/modules/public/configs/selectors.ts
  src/modules/public/configs/types.ts
  src/modules/user/config/actions.test.ts
  src/modules/user/config/actions.ts
  src/modules/user/config/constants.ts
  src/modules/user/config/index.ts
  src/modules/user/config/reducer.test.ts
  src/modules/user/config/reducer.ts
  src/modules/user/config/sagas/configUpdateSaga.test.ts
  src/modules/user/config/sagas/configUpdateSaga.ts
  src/modules/user/config/sagas/index.ts
  src/modules/user/config/selectors.ts
  src/modules/user/config/types.ts
  src/routes/Layout/index.tsx
  src/screens/ChangeForgottenPasswordScreen/index.tsx
  src/screens/EmailVerification/index.tsx
  src/screens/ForgotPassword/index.tsx
  src/screens/SignUpScreen/index.tsx
Labels: Ready

#477 Fix: change sonic config structure according to BE
  mocks/api/v2/sonic/admin/global/secret/OPTIONS.mock
  mocks/api/v2/sonic/admin/global/secret/PUT.mock
  mocks/api/v2/sonic/public/config/GET.mock
  public/config.js
  src/containers/Customization/index.tsx
  src/modules/admin/config/actions.test.ts
  src/modules/admin/config/reducer.test.ts
  src/modules/admin/config/reducer.ts
  src/modules/admin/config/sagas/configUpdateSaga.test.ts
Labels: Ready

#481 Fix: add csrf token to sonic config update
  mocks/api/v2/sonic/admin/global/secret/OPTIONS.mock
  mocks/api/v2/sonic/admin/global/secret/PUT.mock
  src/modules/admin/config/sagas/configUpdateSaga.ts
Labels: Ready

#419 Feature: add internal transfers
  mocks/api/v2/peatio/account/internal_transfers/GET--page=1&limit=25.mock
  mocks/api/v2/peatio/account/internal_transfers/GET.mock
  mocks/api/v2/peatio/account/internal_transfers/OPTIONS.mock
  mocks/api/v2/peatio/account/internal_transfers/POST--currency=btc&username_or_uid=test123&amount=0.1&otp=123456.mock
  mocks/api/v2/sonic/public/config/GET.mock
  src/assets/images/sidebar/SidebarIcons.tsx
  src/components/Dropdown/index.tsx
  src/components/InternalTransfer/InternalInput.tsx
  src/components/InternalTransfer/InternalTransfer.pcss
  src/components/InternalTransfer/index.tsx
  src/components/Markets/__snapshots__/Markets.test.tsx.snap
  src/components/index.ts
  src/components/style.pcss
  src/constants/constants.test.ts
  src/constants/index.ts
  src/containers/HistoryElement/index.tsx
  src/custom/translations/ru.ts
  src/helpers/historyTableUtils.ts
  src/hooks/useHistoryInternalTransferFetch.ts
  src/modules/app.ts
  src/modules/index.ts
  src/modules/user/history/sagas/historySaga.ts
  src/modules/user/internalTransfers/actions.ts
  src/modules/user/internalTransfers/constants.ts
  src/modules/user/internalTransfers/index.ts
  src/modules/user/internalTransfers/reducer.ts
  src/modules/user/internalTransfers/sagas/createInternalTransfersSaga.ts
  src/modules/user/internalTransfers/sagas/index.ts
  src/modules/user/internalTransfers/selectors.ts
  src/routes/Layout/index.tsx
  src/screens/History/index.tsx
  src/screens/InternalTransfer/index.tsx
  src/screens/index.ts
  src/screens/tests/__snapshots__/History.test.tsx.snap
  src/translations/en.ts
Labels: Ready, Required: QA
