Repository openware/baseapp, pull requests merged in 2021-04, with the labels that each got.

#532 Fix: fetchConfigs has already been declared
  web/public/config.js
Labels: Ready

#531 Fix: fetchConfigs has already been declared
  web/public/config.js
Labels: Ready

#552 Fix: close sidebar on landing page
  web/src/containers/Sidebar/index.tsx
Labels: Tech: Approved

#551 Fix: close sidebar on landing page
  web/src/containers/Sidebar/index.tsx
Labels: Ready, Tech: Approved

#550 Fix: blur on trading screen + fix input field for api keys
  src/index.pcss
  src/screens/ProfileScreen/ProfileScreen.pcss
  src/screens/TradingScreen/TradingScreen.pcss
Labels: Ready, Tech: Approved

#547 Fix: blur on trading screen + fix input field for api keys
  web/src/index.pcss
  web/src/screens/ProfileScreen/ProfileScreen.pcss
  web/src/screens/TradingScreen/TradingScreen.pcss
Labels: Ready, Tech: Approved

#546 Fix: [twice fetch config] remove tag script from master.html
  views/layouts/master.html
Labels: Ready, Tech: Approved

#535 Fix: update sorting on numbers in market selector
  web/src/containers/ToolBar/MarketSelector/MarketsList/index.tsx
Labels: Ready, Tech: Approved

#534 Fix: update sorting on numbers in market selector
  web/src/containers/ToolBar/MarketSelector/MarketsList/index.tsx
Labels: Ready, Tech: Approved

#536 Fix: update sorting on numbers in market selector
  src/containers/ToolBar/MarketSelector/MarketsList/index.tsx
Labels: Ready, Tech: Approved

#537 Fix: update sorting on numbers in market selector
  src/containers/ToolBar/MarketSelector/MarketsList/index.tsx
Labels: Ready, Tech: Approved

#538 Fix: update sorting on numbers in market selector
  src/containers/ToolBar/MarketSelector/MarketsList/index.tsx
Labels: Ready, Tech: Approved

#560 Fix: Geetest captcha on sign up
  web/src/containers/GeetestCaptcha/index.tsx
  web/src/screens/SignUpScreen/index.tsx
Labels: QA: Approved, Ready, Tech: Approved

#573 Fix: reset fields after success transfer
  web/src/components/InternalTransfer/index.tsx
  web/src/modules/user/internalTransfers/actions.ts
  web/src/modules/user/internalTransfers/constants.ts
  web/src/modules/user/internalTransfers/reducer.ts
Labels: Ready

#578 Fix: Add shadow color for react-grid-items
  web/src/index.pcss
  web/src/styles/colors.pcss
  web/src/styles/themes/dark.pcss
  web/src/styles/themes/light.pcss
Labels: Ready

#577 Fix: Add shadow color for react-grid-items
  web/src/index.pcss
  web/src/styles/colors.pcss
  web/src/styles/themes/dark.pcss
  web/src/styles/themes/light.pcss
Labels: Ready

#582 Fix: hide p2p wallet if exchange currency disabled
  web/src/containers/Wallets/WalletsP2P/index.tsx
  web/src/containers/Wallets/WalletsTransfer/index.tsx
Labels: Ready

#533 Fix: add logic for hidden markets
  web/mocks/api/v2/finex/public/markets/GET.mock
  web/mocks/api/v2/peatio/public/markets/GET.mock
  web/src/containers/ToolBar/MarketSelector/MarketsList/index.tsx
  web/src/containers/ToolBar/MarketSelector/MarketsTabs/index.tsx
  web/src/screens/TradingScreen/index.tsx
Labels: Ready, Tech: Approved

#526 Fix: add logic for hidden markets
  web/mocks/api/v2/finex/public/markets/GET.mock
  web/mocks/api/v2/peatio/public/markets/GET.mock
  web/src/containers/ToolBar/MarketSelector/MarketsList/index.tsx
  web/src/containers/ToolBar/MarketSelector/MarketsTabs/index.tsx
  web/src/screens/TradingScreen/index.tsx
Labels: Ready

#584 Fix: [transfer history] change receiver
  web/mocks/api/v2/peatio/account/internal_transfers/GET--page=1&limit=25.mock
  web/mocks/api/v2/peatio/account/internal_transfers/GET.mock
  web/src/containers/HistoryElement/index.tsx
Labels: Ready

#587 Fix: wallet search value reset after ws update
  web/src/components/WalletsHeader/index.tsx
  web/src/containers/Wallets/WalletsOverview/index.tsx
  web/src/containers/Wallets/WalletsP2P/index.tsx
  web/src/containers/Wallets/WalletsSpot/index.tsx
  web/src/containers/Wallets/WalletsTransfer/index.tsx
Labels: WIP

#591 Fix: hidden markets
  web/src/containers/Markets/index.tsx
  web/src/containers/MarketsTable/index.tsx
Labels: Ready

#586 Fix: reset internal transfers state
  web/src/components/InternalTransfer/index.tsx
Labels: Ready

#585 Enhancement: Update currencies state in wallets saga
  web/src/custom/translations/ru.ts
  web/src/modules/public/currencies/sagas/currenciesFetchSaga.ts
  web/src/modules/user/wallets/sagas/walletsSaga.ts
  web/src/translations/en.ts
Labels: Ready

#583 Fix: [transfer history] change receiver
  web/mocks/api/v2/peatio/account/internal_transfers/GET--page=1&limit=25.mock
  web/mocks/api/v2/peatio/account/internal_transfers/GET.mock
  web/src/containers/HistoryElement/index.tsx
Labels: Ready

#594 Fix: p2p create offer tab panel background + my offer orders table style
  web/src/containers/P2P/CreateOffer/CreateOffer.pcss
  web/src/containers/P2P/UserOffers/P2PUserOffers.pcss
Labels: Tech: Approved

#595 Fix: PM to which user has to send money, send PM id on sell order create
  web/mocks/api/v2/p2p/private/orders/1/GET.mock
  web/src/containers/P2P/CreateOffer/Step2/index.tsx
  web/src/containers/P2P/Offers/P2POffersModal.tsx
  web/src/containers/P2P/OrderWaitPayment/index.tsx
  web/src/containers/ProfilePayment/index.tsx
  web/src/modules/user/p2pOrders/sagas/updateOrderSaga.ts
  web/src/modules/user/p2pOrders/types.ts
Labels: Ready

#567 Fix: [change password] add action for reset state
  web/src/containers/ProfileAuthDetails/index.tsx
  web/src/modules/user/profile/actions.ts
  web/src/modules/user/profile/constants.ts
  web/src/modules/user/profile/reducer.ts
Labels: Ready, Tech: Approved

#579 Fix: missing filter all in p2p payment method
  web/src/containers/P2P/Offers/P2POffersHeader.tsx
  web/src/screens/P2P/P2POffersScreen/index.tsx
Labels: Ready, Tech: Approved

#601 Fix: hide disabled p2p wallet from transfer list
  web/src/containers/Wallets/WalletsTransfer/index.tsx
Labels: Ready

#596 Fix: buy p2p modal logic for all amount button
  web/src/containers/P2P/Offers/P2POffersModal.tsx
Labels: Ready, Tech: Approved

#598 Fix: [internal transfers] update condition for receiver
  web/src/containers/HistoryElement/index.tsx
Labels: Ready

#599 Fix: [internal transfers] update condition for receiver
  web/src/containers/HistoryElement/index.tsx
Labels: Ready

#581 Fix: change all background images on landing to svg fromat
  web/src/assets/images/landing/PhoneImage.png
  web/src/assets/images/landing/PhoneImage.svg
  web/src/assets/images/landing/TradingUIFullBG.png
  web/src/screens/LandingScreen/LandingScreen.pcss
Labels: Ready, Tech: Approved

#604 Fix: incorrect payment method icon on create new offer step 2
  web/src/containers/P2P/CreateOffer/Step2/index.tsx
Labels: Ready

#600 Fix: incorrect receive amount in confirm order modal
  web/src/containers/P2P/OrderWaitPayment/index.tsx
Labels: Ready

#597 Fix: p2p trade history counter party value
  web/src/containers/P2P/TradesHistory/index.tsx
Labels: Ready

#603 Fix: handle maintenance and restriction pages
  handlers/index.go
  views/maintenance.html
  views/restriction.html
  web/public/config.js
  web/src/containers/Header/index.tsx
  web/src/routes/Layout/index.tsx
Labels: Ready
