Repository openware/baseapp, pull requests merged in 2021-06, with the labels that each got.

#671 Fix: missing translation wallets balance
  web/src/custom/translations/ru.ts
  web/src/translations/en.ts
Labels: Ready

#674 Fix: (mobile) missing header on home page
  web/src/mobile/components/Header/index.tsx
Labels: Ready

#660 Fix: update withdraw history when withdrawal request succeed
  web/src/containers/Wallets/History.tsx
Labels: QA: Approved, Ready

#681 Feature: add CanCanCan + fetch abilities from finex (#777)
  web/mocks/api/v2/finex/abilities/GET.mock
  web/src/constants/constants.test.ts
  web/src/constants/index.ts
  web/src/containers/CanCan/index.tsx
  web/src/containers/Sidebar/index.tsx
  web/src/containers/index.ts
  web/src/helpers/index.ts
  web/src/helpers/mergeObjects.ts
  web/src/modules/app.ts
  web/src/modules/index.ts
  web/src/modules/user/abilities/actions.test.ts
  web/src/modules/user/abilities/actions.ts
  web/src/modules/user/abilities/constants.ts
  web/src/modules/user/abilities/index.ts
  web/src/modules/user/abilities/reducer.test.ts
  web/src/modules/user/abilities/reducer.ts
  web/src/modules/user/abilities/sagas/abilitiesSaga.ts
  web/src/modules/user/abilities/sagas/index.ts
  web/src/modules/user/abilities/selectors.ts
  web/src/modules/user/profile/sagas/userSaga.ts
  web/src/routes/Layout/index.tsx
  web/src/screens/History/index.tsx
Labels: Ready, Tech: Approved

#682 Feature: add warning message for deposit
  web/mocks/api/v2/peatio/public/currencies/GET.mock
  web/src/components/Beneficiaries/BeneficiariesCrypto/SelectBeneficiariesCrypto.tsx
  web/src/components/DepositCrypto/index.tsx
  web/src/components/WarningMessage/WarningMessage.pcss
  web/src/components/WarningMessage/index.tsx
  web/src/components/index.ts
  web/src/components/style.pcss
  web/src/containers/Wallets/Deposit/DepositCryptoContainer/DepositCryptoContainer.pcss
  web/src/containers/Wallets/Deposit/DepositCryptoContainer/index.tsx
  web/src/containers/Wallets/WalletsSpot/index.tsx
  web/src/custom/translations/ru.ts
  web/src/mobile/components/WalletDepositBody/index.tsx
  web/src/modules/public/withdrawLimits/sagas/withdrawLimitsSaga.ts
  web/src/modules/user/withdrawLimit/sagas/withdrawLimitSaga.ts
  web/src/translations/en.ts
Labels: Ready, WIP

#691 Fix: hide currency with status hidden
  web/mocks/api/v2/peatio/public/config/GET.mock
  web/mocks/api/v2/peatio/public/currencies/GET.mock
  web/src/containers/Wallets/WalletsOverview/index.tsx
  web/src/containers/Wallets/WalletsSpot/index.tsx
  web/src/helpers/estimateValue.ts
  web/src/modules/public/currencies/reducer.test.ts
  web/src/modules/public/currencies/types.ts
  web/src/modules/user/wallets/sagas/p2pWalletsSaga.ts
  web/src/modules/user/wallets/sagas/walletsSaga.ts
Labels: Ready

#712 Fix: remove p2p from sidebar items for 3.0
  web/src/constants/index.ts
Labels: Ready
