Repository openware/baseapp, pull requests merged in 2021-05, with the labels that each got.

#611 Fix: disable click for cancelled p2p order in history list
  web/src/containers/P2P/TradesHistory/index.tsx
Labels: Ready

#615 Fix: add alert after submit dispute
  web/src/custom/translations/ru.ts
  web/src/modules/user/p2pDispute/sagas/createP2PDisputesSaga.ts
  web/src/translations/en.ts
Labels: Ready

#617 Fix: handle magic link in configs
  web/public/config.js
  web/src/api/config.ts
Labels: QA: Approved, Ready

#619 Fix: template customize button overlap p2p list
  web/src/screens/P2P/P2POffersScreen/P2POffersScreen.pcss
Labels: Ready

#620 Fix: add asset/fiat column to p2p history
  web/src/containers/P2P/TradesHistory/index.tsx
  web/src/custom/translations/ru.ts
  web/src/translations/en.ts
Labels: Ready

#621 Fix: offer completion rate precision
  web/src/containers/P2P/Offers/index.tsx
Labels: Ready

#622 Fix: show zero completion percentage for offer
  web/src/containers/P2P/Offers/index.tsx
Labels: Ready

#625 Fix: max order limit exceed offer available
  web/src/containers/P2P/Offers/P2POffersModal.tsx
Labels: Ready

#627 Fix: p2p sell order all button amount calculation
  web/src/containers/P2P/Offers/P2POffersModal.tsx
Labels: Ready

#632 Fix: change route for docs
  web/src/constants/index.ts
  web/src/routes/Layout/index.tsx
Labels: Ready

#636 Fix: update redux for internal transfers
  web/src/components/InternalTransfer/index.tsx
  web/src/modules/user/internalTransfers/reducer.ts
Labels: Ready

#571 Fix: ssr - add favicon
  views/layouts/master.html
Labels: Ready, Required: Review

#644 Fix: continuous markets loading
  web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
  web/src/containers/Wallets/EstimatedValue/index.tsx
  web/src/containers/Wallets/WalletsOverview/index.tsx
  web/src/containers/Wallets/WalletsP2P/index.tsx
  web/src/containers/Wallets/WalletsSpot/index.tsx
  web/src/containers/Wallets/WalletsTransfer/index.tsx
Labels: Ready

#649 Fix: add translation for invalid totp error
  web/src/custom/translations/ru.ts
  web/src/translations/en.ts
Labels: Ready

#647 Ehnancement: Change placeholder for date
  web/src/custom/translations/ru.ts
  web/src/translations/en.ts
Labels: Ready, Tech: Approved

#650 Fix: redirect allowed user from /restriction, /maintenance page
  handlers/index.go
  web/public/config.js
Labels: Ready

#646 Fix: Rewrite market depths with hooks, update webpack config to prevent recharts crash
  web/src/containers/MarketDepth/index.tsx
  web/webpack/common.ts
Labels: Ready, Tech: Approved

#651 Fix: estimated value style in wallet page
  web/src/containers/Wallets/EstimatedValue/EstimatedValue.pcss
Labels: Ready

#648 Fix: use CodeVerification component for login 2fa form
  web/src/components/TwoFactorAuth/TwoFactorAuth.test.tsx
  web/src/components/TwoFactorAuth/index.tsx
  web/src/containers/ProfileApiKeys/index.tsx
  web/src/custom/translations/ru.ts
  web/src/screens/SignInScreen/index.tsx
  web/src/translations/en.ts
Labels: Ready

#652 Fix: restore Footer for mobile app
  web/src/App.tsx
  web/src/mobile/components/Footer/index.tsx
  web/src/mobile/styles/components/Footer.pcss
  web/src/mobile/styles/components/styles.pcss
Labels: Ready, Tech: Approved

#643 Fix: login without refreshing should also start check login status
  web/src/modules/user/auth/sagas/logoutSaga.ts
  web/src/routes/Layout/index.tsx
Labels: QA: Approved

#641 Fix: validate kyc address upload min, max file size
  web/src/api/config.ts
  web/src/api/types.ts
  web/src/components/UploadFile/UploadFile.pcss
  web/src/components/UploadFile/index.tsx
  web/src/containers/Confirm/Address/index.tsx
  web/src/containers/Confirm/Documents/index.tsx
  web/src/custom/translations/ru.ts
  web/src/translations/en.ts
Labels: QA: Approved, Ready, Tech: Approved

#658 Fix: deposit history BitGo confirmations count "N/A"
  web/mocks/api/v2/peatio/account/deposits/GET.mock
  web/src/containers/Wallets/History.tsx
  web/src/modules/user/history/types.ts
Labels: Tech: Approved

#653 Fix: show alert message when create beneficiaries error
  web/src/modules/public/alert/sagas/handleAlertSaga.ts
Labels: QA: Approved, Ready, Tech: Approved

#633 Fix: change route for docs
  web/src/constants/index.ts
  web/src/routes/Layout/index.tsx
Labels: Ready

#618 Feature: Add themeSwitcher env to configs, display themeSwitcher depe…
  web/mocks/api/v2/sonic/public/config/GET.mock
  web/src/api/config.ts
  web/src/api/types.ts
  web/src/containers/NavBar/index.tsx
  web/src/helpers/jest.ts
Labels: Ready

#616 Fix: handle magic link in configs
  web/public/config.js
  web/src/api/config.ts
Labels: QA: Approved, Ready

#562 Fix: ssr - add condition for rendering default footer
  handlers/index.go
  views/layouts/master.html
Labels: Ready, Required: Review

#628 Fix: [open orders] change init amount to remaining amount
  web/src/containers/OpenOrders/index.tsx
Labels: Ready, Tech: Approved

#635 Fix: [internal transfer] reset value
  web/src/components/Dropdown/index.tsx
  web/src/components/InternalTransfer/index.tsx
  web/src/modules/user/internalTransfers/reducer.ts
Labels: Ready, Tech: Approved

#630 Fix: [otp modal - api] rename button
  web/src/custom/translations/ru.ts
  web/src/translations/en.ts
Labels: Ready

#569 Fix: add condition for recaptcha
  web/src/components/Captcha/index.tsx
Labels: Ready, Required: Review
