Repository openware/baseapp, pull requests merged in 2021-01, with the labels that each got.

#402 Feature: add peatio user api documentation
  mocks/api/v2/peatio/swagger/GET.mock
  package.json
  src/assets/images/sidebar/SidebarIcons.tsx
  src/components/Documentation/Documentation.pcss
  src/components/Documentation/Endpoints/DocumentationEndpoints.pcss
  src/components/Documentation/Endpoints/Item/RequestTypeItem/ParametersItem/index.tsx
  src/components/Documentation/Endpoints/Item/RequestTypeItem/ResponsesItem/index.tsx
  src/components/Documentation/Endpoints/Item/RequestTypeItem/index.tsx
  src/components/Documentation/Endpoints/Item/index.tsx
  src/components/Documentation/Endpoints/index.tsx
  src/components/Documentation/Header/DocumentationHeader.pcss
  src/components/Documentation/Header/index.tsx
  src/components/Documentation/Models/DocumentationModels.pcss
  src/components/Documentation/Models/Item/DocumentationModelsItem.pcss
  src/components/Documentation/Models/Item/index.tsx
  src/components/Documentation/Models/index.tsx
  src/components/Documentation/index.ts
  src/components/index.ts
  src/components/style.pcss
  src/constants/constants.test.ts
  src/constants/index.ts
  src/containers/Sidebar/Sidebar.pcss
  src/custom/translations/ru.ts
  src/hooks/index.ts
  src/hooks/useDocumentationFetch.ts
  src/modules/app.ts
  src/modules/index.ts
  src/modules/user/documentation/actions.test.ts
  src/modules/user/documentation/actions.ts
  src/modules/user/documentation/constants.ts
  src/modules/user/documentation/index.ts
  src/modules/user/documentation/reducer.test.ts
  src/modules/user/documentation/reducer.ts
  src/modules/user/documentation/sagas/docTradeUserApiFetchSaga.test.ts
  src/modules/user/documentation/sagas/docTradeUserApiFetchSaga.ts
  src/modules/user/documentation/sagas/index.ts
  src/modules/user/documentation/selectors.ts
  src/modules/user/documentation/types.ts
  src/routes/Layout/index.tsx
  src/screens/DocumentationScreen/DocumentationScreen.pcss
  src/screens/DocumentationScreen/index.tsx
  src/screens/index.ts
  src/screens/style.pcss
  src/translations/en.ts
  yarn.lock
Labels: Ready, Tech: Approved

#400 Fix: scale incremental orderbook limit to avoid price holes
  src/modules/public/orderBook/reducer.ts
Labels: Ready, Tech: Approved

#415 Fix: handle API Key error in reducer
  src/modules/user/apiKeys/reducer.ts
Labels: Ready

#417 Fix: solve translations overwriting issue
  src/custom/translations/index.ts
  src/custom/translations/ru.ts
  src/translations/en.ts
  src/translations/index.ts
Labels: Optimization, Ready

#397 Feature: max 10 beneficiary addresses according to BE
  mocks/api/v2/peatio/account/beneficiaries/10/activate/PATCH.mock
  mocks/api/v2/peatio/account/beneficiaries/10/activate/POST.mock
  mocks/api/v2/peatio/account/beneficiaries/GET.mock
  mocks/api/v2/peatio/account/beneficiaries/POST.mock
  src/components/Beneficiaries/Beneficiaries.pcss
  src/components/Beneficiaries/index.tsx
  src/custom/translations/ru.ts
  src/modules/public/errorHandler/sagas/handleErrorSaga.ts
  src/modules/user/beneficiaries/actions.test.ts
  src/modules/user/beneficiaries/actions.ts
  src/modules/user/beneficiaries/sagas/beneficiariesSaga.ts
  src/screens/WalletsScreen/index.tsx
  src/translations/en.ts
Labels: 2.7

#421 Feature: Add nickname field to the UserData
  mocks/api/v2/barong/identity/sessions/POST--email=admin@barong.io&password=123123&otp_code=&recaptcha_response=.mock
  mocks/api/v2/barong/identity/sessions/POST--email=otp@peatio.tech&password=123123&otp_code=123456&recaptcha_response=.mock
  mocks/api/v2/barong/identity/sessions/POST--email=user1@peatio.tech&password=123123&otp_code=&recaptcha_response=.mock
  mocks/api/v2/barong/identity/sessions/POST--email=user2@peatio.tech&password=123123&otp_code=&recaptcha_response=.mock
  mocks/api/v2/barong/resource/users/me/GET.mock
  public/config/env.js
  src/api/config.ts
  src/api/types.ts
  src/components/SignUp/SignUp.test.tsx
  src/components/SignUp/index.tsx
  src/containers/ProfileAuthDetails/index.tsx
  src/custom/translations/ru.ts
  src/helpers/index.ts
  src/helpers/jest.ts
  src/helpers/nicknameValidation.ts
  src/modules/user/auth/actions.ts
  src/modules/user/auth/sagas/signInSaga.test.ts
  src/modules/user/profile/actions.test.ts
  src/modules/user/profile/reducer.test.ts
  src/modules/user/profile/reducer.ts
  src/modules/user/profile/sagas/changeUserDataSaga.test.ts
  src/modules/user/profile/sagas/userSaga.test.ts
  src/modules/user/profile/types.ts
  src/screens/ProfileScreen/ProfileScreen.pcss
  src/screens/SignUpScreen/index.tsx
  src/translations/en.ts
Labels: Ready, Tech: Approved

#420 Fix: phone verification sendcode logic should cover resend too
  mocks/api/v2/barong/resource/phones/OPTIONS.mock
  mocks/api/v2/barong/resource/phones/POST--phone_number=+1111.mock
  mocks/api/v2/barong/resource/phones/POST--phone_number=+1234.mock
  mocks/api/v2/barong/resource/phones/send_code/OPTIONS.mock
  mocks/api/v2/barong/resource/phones/send_code/POST.mock
  src/modules/user/kyc/phone/sagas/sendCodeSaga.ts
Labels: Ready, Tech: Approved

#422 Feature: add landing blocks
  package.json
  src/index.tsx
  src/screens/LandingScreen/LandingScreen.pcss
  src/screens/LandingScreen/index.tsx
  yarn.lock
Labels: Required: FIX

#425 Fix: trade page market selector search field overflow
  src/containers/ToolBar/MarketSelector/MarketSelector.pcss
  src/containers/ToolBar/ToolBar.pcss
Labels: Ready

#424 Fix: nickname validation fixes
  src/components/SignUp/index.tsx
  src/containers/ProfileAuthDetails/index.tsx
  src/custom/translations/ru.ts
  src/helpers/nicknameValidation.ts
  src/screens/SignUpScreen/SignUpScreen.pcss
  src/screens/SignUpScreen/index.tsx
  src/styles/colors.pcss
  src/translations/en.ts
Labels: Required: Review

#433 Fix: unify email forms styles
  src/components/Beneficiaries/Beneficiaries.pcss
  src/components/Captcha/Captcha.pcss
  src/components/ChangePassword/ChangePassword.pcss
  src/components/EmailForm/EmailForm.pcss
  src/components/SignIn/SignIn.pcss
  src/components/SignUp/SignUp.pcss
  src/containers/ChangePassword/ChangePassword.pcss
  src/screens/ForgotPassword/ForgotPassword.pcss
  src/screens/ProfileScreen/ProfileScreen.pcss
  src/screens/SignInScreen/SignInScreen.pcss
  src/screens/SignUpScreen/SignUpScreen.pcss
  src/styles/themes/dark.pcss
  src/styles/themes/light.pcss
Labels: Ready

#434 Fix: profile kyc naming
  src/components/Markets/__snapshots__/Markets.test.tsx.snap
  src/custom/translations/ru.ts
  src/translations/en.ts
Labels: Required: Review

#439 Fix: polish Recent Trades after wrong rebase
  src/containers/RecentTrades/Market.tsx
  src/containers/RecentTrades/RecentTradesTableCell.tsx
  src/containers/RecentTrades/Yours.tsx
Labels: Ready

#442 Fix: close sidebar on KYC pages (regression issue)
  src/screens/ConfirmScreen/index.tsx
Labels: Ready

#440 Feature: Add destination tag field for xrp, add validation of some currency addresses
  src/components/Beneficiaries/Beneficiaries.pcss
  src/components/Beneficiaries/BeneficiariesAddModal.tsx
  src/components/Markets/__snapshots__/Markets.test.tsx.snap
  src/custom/translations/ru.ts
  src/helpers/validateBeneficiaryAddress.test.ts
  src/helpers/validateBeneficiaryAddress.ts
  src/translations/en.ts
Labels: Ready

#436 Fix: wallets currency item consistency when the currency icon_url exists
  mocks/api/v2/peatio/public/currencies/GET.mock
  src/components/CryptoIcon/__snapshots__/CryptoIcon.test.tsx.snap
  src/components/CryptoIcon/index.tsx
  src/components/CurrencyInfo/index.tsx
  src/components/WalletItem/__snapshots__/WalletItem.test.tsx.snap
  src/components/WalletItem/index.tsx
Labels: Ready

#435 Fix: adjust 2fa layout for russian lang
  src/screens/ProfileTwoFactorAuthScreen/ProfileTwoFactorAuthScreen.pcss
  src/screens/ProfileTwoFactorAuthScreen/index.tsx
  src/screens/tests/__snapshots__/ProfileTwoFactorAuthScreen.test.tsx.snap
Labels: Required: Review

#443 Fix: Email verification styles (regression bug)
  src/components/PasswordStrengthMeter/PasswordStrengthMeter.pcss
  src/components/SignUp/SignUp.pcss
  src/containers/ReferralProgram/ReferralProgram.pcss
  src/screens/EmailVerification/EmailVerification.pcss
  src/screens/ProfileScreen/ProfileScreen.pcss
  src/screens/SignInScreen/index.tsx
Labels: Ready

#445 Fix: add missing translations for doc expire
  src/components/Markets/__snapshots__/Markets.test.tsx.snap
  src/custom/translations/ru.ts
  src/translations/en.ts
Labels: Ready
