Repository openware/baseapp, pull requests merged in 2021-10, with the labels that each got.

#816 Fix: do not allow to select disabled network in add beneficiary modal
  web/src/components/Beneficiaries/DropdownBeneficiary.tsx
Labels: Tech: Approved

#815 Fix: internal transfer currency dropdown
  web/src/components/InternalTransfer/InternalTransfer.pcss
Labels: Ready, Tech: Approved

#814 Fix: wallet total estimated value calculation
  web/mocks/api/v2/peatio/public/config/GET.mock
  web/src/containers/Wallets/WalletsOverview/index.tsx
  web/src/helpers/estimateValue.ts
Labels: Ready, Tech: Approved

#813 Fix: add history quick exchange tab
  web/mocks/api/v2/peatio/market/orders/GET--page=1&limit=25&market_type=qe.mock
  web/src/containers/HistoryElement/index.tsx
  web/src/custom/translations/ru.ts
  web/src/helpers/historyTableUtils.ts
  web/src/modules/user/history/actions.ts
  web/src/modules/user/history/sagas/historySaga.ts
  web/src/translations/en.ts
Labels: Ready, Tech: Approved

#817 Fix: show blockchain network on withdraw confirmation window
  web/mocks/api/v2/peatio/account/beneficiaries/GET--currency_id=btc&state[]=active&state[]=pending.mock
  web/src/containers/ModalWithdrawConfirmation/index.tsx
  web/src/containers/Wallets/WalletsSpot/index.tsx
  web/src/modules/user/beneficiaries/types.ts
Labels: Ready, Tech: Approved

#818 Fix: added hidden status for deposit and updated fiat beneficiaries
  web/mocks/api/v2/peatio/account/beneficiaries/GET--currency_id=usd&state[]=active&state[]=pending.mock
  web/mocks/api/v2/peatio/public/config/GET.mock
  web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
  web/src/components/Beneficiaries/BeneficiariesCrypto/SelectBeneficiariesCrypto.tsx
  web/src/components/Markets/__snapshots__/Markets.test.tsx.snap
  web/src/containers/Wallets/Deposit/DepositCryptoContainer/index.tsx
  web/src/containers/Wallets/History.tsx
  web/src/custom/translations/ru.ts
  web/src/helpers/historyTableUtils.ts
  web/src/screens/tests/__snapshots__/WalletsScreen.test.tsx.snap
  web/src/translations/en.ts
Labels: Ready

#822 Fix: clear only 2fa input when create beneficiary failed
  web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
Labels: Ready

#821 Fix: withdraw history under review status
  web/mocks/api/v2/peatio/account/withdraws/GET.mock
  web/src/containers/Wallets/History.tsx
  web/src/custom/translations/ru.ts
  web/src/translations/en.ts
Labels: Ready

#823 Fix: internal transfer 2fa overlay
  web/src/components/InternalTransfer/InternalTransfer.pcss
Labels: Ready

#825 Fix: open explorer link for deposit and withdraw transaction
  web/mocks/api/v2/peatio/account/deposits/GET--page=1&currency=btc&limit=6.mock
  web/mocks/api/v2/peatio/account/deposits/GET--page=1&currency=eth&limit=6.mock
  web/mocks/api/v2/peatio/account/withdraws/GET--page=1&currency=btc&limit=6.mock
  web/mocks/api/v2/peatio/public/config/GET.mock
  web/src/containers/Wallets/History.tsx
Labels: Ready
