Repository openware/baseapp, pull requests merged in 2021-03, with the labels that each got.

#487 Feature: trigger Assembly line with custom baseapp
  .drone.yml
Labels: 2.6

#486 Fix required node version and missed npm package (#485)
  .nvmrc
  package.json
  yarn.lock
Labels: Ready

#483 Fix: Update wizard pages
  mocks/api/v2/barong/identity/users/POST--email=admin@barong.io&password=Qwerty12345.mock
  public/config.js
  src/api/config.ts
  src/components/SetupComponents/SetupFormBlock/SetupFormBlock.pcss
  src/components/SetupComponents/SetupFormInput/SetupFormInput.pcss
  src/components/SetupComponents/SetupGeneralSettingsForm/index.tsx
  src/components/SetupComponents/SetupInfoBlock/SetupInfoBlock.pcss
  src/components/SetupComponents/SetupLoginForm/index.tsx
  src/components/SetupComponents/SetupMarketsBlock/SetupMarketsBlock.pcss
  src/components/SetupComponents/SetupMarketsBlock/index.tsx
  src/components/SetupComponents/SetupRegisterForm/index.tsx
  src/helpers/emailValidation.ts
  src/modules/admin/platform/actions.ts
  src/modules/admin/platform/constants.ts
  src/modules/admin/platform/index.ts
  src/modules/admin/platform/reducer.ts
  src/modules/admin/platform/sagas/index.ts
  src/modules/admin/platform/sagas/platformDataCreateSaga.ts
  src/modules/admin/platform/selectors.ts
  src/modules/app.ts
  src/modules/index.ts
  src/modules/user/auth/actions.ts
  src/modules/user/auth/sagas/signUpSaga.ts
  src/screens/SetupScreen/SetupScreen.pcss
  src/screens/SetupScreen/colors.pcss
  src/screens/SetupScreen/fonts.pcss
  src/screens/SetupScreen/index.tsx
Labels: Ready

#488 Feature: Global Wizard pages update
  mocks/api/v2/sonic/public/config/GET.mock
  public/config.js
  src/App.tsx
  src/components/SetupComponents/SetupFormInput/SetupFormInput.pcss
  src/components/SetupComponents/SetupFormInput/index.tsx
  src/components/SetupComponents/SetupGeneralSettingsForm/index.tsx
  src/components/SetupComponents/SetupLoginForm/index.tsx
  src/components/SetupComponents/SetupMarketsBlock/SetupMarketsBlock.pcss
  src/components/SetupComponents/SetupMarketsBlock/index.tsx
  src/components/SetupComponents/SetupRegisterForm/index.tsx
  src/containers/Footer/Footer.pcss
  src/containers/Footer/index.tsx
  src/containers/index.ts
  src/containers/style.pcss
  src/mobile/components/Footer/index.tsx
  src/mobile/components/index.ts
  src/mobile/styles/components/Footer.pcss
  src/mobile/styles/components/styles.pcss
  src/modules/admin/markets/actions.ts
  src/modules/admin/markets/constants.ts
  src/modules/admin/markets/reducer.ts
  src/modules/admin/markets/sagas/updateMarketSaga.ts
  src/modules/admin/platform/actions.ts
  src/modules/admin/platform/sagas/platformDataCreateSaga.ts
  src/modules/user/auth/reducer.ts
  src/modules/user/auth/sagas/signUpSaga.ts
  src/modules/user/auth/selectors.ts
  src/routes/Layout/index.tsx
  src/screens/SetupScreen/SetupScreen.pcss
  src/screens/SetupScreen/colors.pcss
  src/screens/SetupScreen/index.tsx
  yarn.lock
Labels: Ready

#489 Feature: add images customization
  mocks/api/v2/barong/identity/sessions/POST.mock
  src/assets/images/LogoIcon.tsx
  src/components/Customization/Images/ImageSettings/index.tsx
  src/components/Customization/Images/Images.pcss
  src/components/Customization/Images/index.tsx
  src/components/Customization/Themes/index.tsx
  src/components/Customization/style.pcss
  src/components/Logo/index.tsx
  src/components/Markets/__snapshots__/Markets.test.tsx.snap
  src/components/index.ts
  src/containers/Customization/colors.pcss
  src/containers/Customization/index.tsx
  src/containers/Header/Header.pcss
  src/containers/Header/index.tsx
  src/containers/NavBar/NavBar.pcss
  src/containers/Sidebar/Sidebar.pcss
  src/custom/translations/ru.ts
  src/mobile/components/Header/index.tsx
  src/mobile/styles/components/Header.pcss
  src/modules/public/globalSettings/actions.ts
  src/modules/public/globalSettings/constants.ts
  src/modules/public/globalSettings/reducer.test.ts
  src/modules/public/globalSettings/reducer.ts
  src/modules/public/globalSettings/selectors.ts
  src/screens/ConfirmScreen/ConfirmScreen.pcss
  src/screens/ConfirmScreen/index.tsx
  src/screens/LandingScreen/LandingScreen.pcss
  src/screens/LandingScreen/index.tsx
  src/screens/MaintenanceScreen/MaintenanceScreen.pcss
  src/screens/MaintenanceScreen/index.tsx
  src/screens/tests/__snapshots__/ConfirmScreen.test.tsx.snap
  src/screens/tests/__snapshots__/MaintenanceScreen.test.tsx.snap
  src/themes/types.ts
  src/translations/en.ts
Labels: Ready

#496 Feature: add combined charts component
  src/containers/Charts/Charts.pcss
  src/containers/Charts/index.tsx
  src/containers/Footer/Footer.pcss
  src/containers/MarketDepth/MarketDepth.pcss
  src/containers/MarketDepth/index.tsx
  src/containers/ToolBar/ToolBar.pcss
  src/containers/TradingChart/TradingChart.pcss
  src/containers/TradingChart/index.tsx
  src/containers/index.ts
  src/containers/style.pcss
  src/custom/translations/ru.ts
  src/helpers/layout.ts
  src/screens/TradingScreen/index.tsx
  src/translations/en.ts
  yarn.lock
Labels: 2.6, Ready

#491 Fix: polish customization and platform setup UI
  web/.gitignore
  web/src/components/SetupComponents/SetupFormInput/SetupFormInput.pcss
  web/src/components/SetupComponents/SetupRegisterForm/SetupRegisterForm.pcss
  web/src/containers/Customization/index.tsx
  web/src/screens/SetupScreen/SetupScreen.pcss
  web/src/themes/Presets.ts
Labels: Ready

#500 Feature: use last trade to display market price in order book
  mocks/ranger.js
  src/containers/OrderBook/index.tsx
  src/modules/index.ts
  src/modules/public/recentTrades/reducer.test.ts
  src/modules/public/recentTrades/reducer.ts
  src/modules/public/recentTrades/selectors.ts
  src/modules/user/history/types.ts
Labels: 2.6, Required: QA

#504 Fix: send correct param refid on signup
  web/src/screens/SignUpScreen/index.tsx
Labels: 2.6, Ready

#510 Enhancement: Improve regex for platform url
  web/src/assets/images/sidebar/SidebarIcons.tsx
  web/src/helpers/emailValidation.ts
Labels: Ready

#514 Fix: refactor websockets connection
  src/containers/MarketsTable/index.tsx
  src/containers/Wallets/EstimatedValue/index.tsx
  src/hooks/index.ts
  src/hooks/useRangerConnectFetch.ts
  src/mobile/screens/Orders/index.tsx
  src/mobile/screens/Trading/index.tsx
  src/mobile/screens/WalletDeposit/index.tsx
  src/modules/public/ranger/index.ts
  src/modules/public/ranger/reducer.test.ts
  src/modules/public/ranger/reducer.ts
  src/modules/public/ranger/sagas/rangerSaga.test.ts
  src/modules/public/ranger/selectors.ts
  src/modules/user/auth/sagas/logoutSaga.test.ts
  src/routes/Layout/index.tsx
  src/screens/OrdersTabScreen/index.tsx
  src/screens/TradingScreen/index.tsx
Labels: 2.6, Ready

#516 Fix: add fiat beneficiary address label
  web/src/custom/translations/ru.ts
  web/src/translations/en.ts
Labels: Tech: Approved

#508 Enhancement: Add latest sonic changes
  .gitignore
  README.md
  daemons/common_test.go
  daemons/license.go
  daemons/markets.go
  daemons/markets_test.go
  go.mod
  go.sum
  handlers/admin.go
  handlers/helpers.go
  handlers/index.go
  handlers/middlewares.go
  web/src/components/CombinedOrderBook/CombinedOrderBook.test.tsx
  web/src/components/CombinedOrderBook/index.tsx
  web/src/components/SetupComponents/SetupGeneralSettingsForm/index.tsx
  web/src/components/SetupComponents/SetupRegisterForm/index.tsx
  web/src/containers/OrderBook/index.tsx
  web/src/modules/public/orderBook/actions.ts
  web/src/modules/public/orderBook/constants.ts
  web/src/modules/public/orderBook/reducer.ts
  web/src/modules/public/orderBook/selectors.ts
  web/src/modules/public/orderBook/types.ts
  web/src/screens/SetupScreen/index.tsx
Labels: Ready

#447 Feature: Rework Beneficiaries component, Fix captcha on Login
  .drone.yml
  web/src/components/Beneficiaries/Beneficiaries.pcss
  web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
  web/src/components/Beneficiaries/index.tsx
  web/src/components/SignIn/index.tsx
  web/src/containers/Wallets/History.tsx
  web/src/custom/translations/ru.ts
  web/src/hooks/index.ts
  web/src/modules/user/beneficiaries/actions.ts
  web/src/modules/user/beneficiaries/constants.ts
  web/src/modules/user/beneficiaries/reducer.ts
  web/src/screens/SignInScreen/index.tsx
  web/src/translations/en.ts
Labels: Ready, Tech: Approved

#521 Enhancement: Fix geetest captcha
  web/src/containers/GeetestCaptcha/index.tsx
  web/src/helpers/geetest.js
  web/src/helpers/geetest.js.txt
Labels: Ready
