Repository openware/baseapp, pull requests merged in 2021-07, with the labels that each got.

#699 Fix: make bech32 btc address valid in cryptoRegExp
  web/src/components/Beneficiaries/Beneficiaries.pcss
  web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
  web/src/custom/translations/ru.ts
  web/src/helpers/index.ts
  web/src/helpers/validateBeneficiaryAddress.test.ts
  web/src/helpers/validateBeneficiaryAddress.ts
  web/src/helpers/validateBeneficiaryTestnetAddress.test.ts
  web/src/helpers/validateBeneficiaryTestnetAddress.ts
  web/src/translations/en.ts
Labels: Tech: Approved

#713 Fix: add price precision for data in table on landing page
  web/src/components/TickerTable/index.tsx
  web/src/constants/index.ts
Labels: Required: Review

#694 Fix: beneficiaries add permission error alert (3-0-stable)
  web/mocks/api/v2/peatio/account/beneficiaries/POST--currency_id=btc&name=test&data.address=1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY.mock
  web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
  web/src/modules/public/alert/sagas/handleAlertSaga.ts
Labels: QA: Approved

#711 Feature: add error translation for barong rack-attack error
  web/src/custom/translations/ru.ts
  web/src/modules/public/alert/sagas/handleAlertSaga.ts
  web/src/translations/en.ts
Labels: Ready

#721 Improvement: loading state of button after submit on KYC
  web/src/containers/Confirm/Address/index.tsx
  web/src/containers/Confirm/Documents/index.tsx
  web/src/containers/Confirm/Identity/index.tsx
  web/src/containers/Confirm/Phone/Phone.pcss
  web/src/containers/Confirm/Phone/index.tsx
  web/src/modules/user/kyc/documents/actions.ts
  web/src/modules/user/kyc/documents/reducer.ts
  web/src/modules/user/kyc/documents/sagas/sendDocumentsSaga.test.ts
  web/src/modules/user/kyc/documents/sagas/sendDocumentsSaga.ts
  web/src/modules/user/kyc/identity/reducer.test.ts
  web/src/modules/user/kyc/identity/reducer.ts
  web/src/modules/user/kyc/identity/selectors.ts
  web/src/modules/user/kyc/phone/reducer.test.ts
  web/src/modules/user/kyc/phone/reducer.ts
  web/src/modules/user/kyc/phone/selectors.ts
  web/src/screens/ConfirmScreen/ConfirmScreen.pcss
Labels: Ready

#723 Fix: fix markup on orders
  web/src/components/Decimal/index.tsx
  web/src/components/TabPanel/index.tsx
  web/src/containers/RecentTrades/index.tsx
  web/src/mobile/components/Orders/OrdersItem.tsx
  web/src/mobile/components/Orders/index.tsx
  web/src/mobile/components/TradingTabs/index.tsx
  web/src/mobile/styles/components/Orders.pcss
  web/src/mobile/styles/components/OrdersItem.pcss
  web/src/mobile/translations/en.ts
  web/src/mobile/translations/ru.ts
Labels: Ready

#724 Improvement: hide deposit for not verified user
  web/src/components/Blur/Blur.pcss
  web/src/components/Blur/index.tsx
  web/src/custom/translations/ru.ts
  web/src/hooks/index.ts
  web/src/hooks/useMemberLevelsFetch.ts
  web/src/mobile/components/WalletDepositBody/index.tsx
  web/src/mobile/components/WalletWithdrawBody/index.tsx
  web/src/mobile/screens/WalletDeposit/index.tsx
  web/src/mobile/screens/WalletWithdraw/index.tsx
  web/src/mobile/styles/components/WalletWithdrawBody.pcss
  web/src/screens/WalletsScreen/WalletsScreen.pcss
  web/src/screens/WalletsScreen/index.tsx
  web/src/translations/en.ts
Labels: QA: Approved, Required: Review

#727 Fix: Red theme color, Withdraw & Profile minor styles
  web/mocks/api/v2/barong/resource/api_keys/OPTIONS.mock
  web/mocks/api/v2/barong/resource/api_keys/POST.mock
  web/src/components/Beneficiaries/Beneficiaries.pcss
  web/src/components/Markets/__snapshots__/Markets.test.tsx.snap
  web/src/containers/ProfileVerification/ProfileVerification.pcss
  web/src/mobile/components/WalletDepositBody/index.tsx
  web/src/themes/templates/dark/Red.tsx
Labels: QA: Approved

#728 Fix: ordering of Withdraw Warning messages
  web/src/containers/Wallets/WalletsSpot/index.tsx
Labels: Required: Review

#730 Fix: add set new chart for tvWidget
  web/src/containers/TradingChart/index.tsx
Labels: Tech: Approved
