Repository openware/baseapp, pull requests merged in 2021-09, with the labels that each got.

#762 Fix: fetch beneficiary on withdraw tab
  web/src/containers/Wallets/WalletsSpot/index.tsx
Labels: Ready

#764 Fix: input style on wallet deposit tab
  web/src/assets/images/CopyIcon.tsx
  web/src/components/CopyableTextField/CopyableTextField.pcss
  web/src/components/CustomInput/CustomInput.pcss
  web/src/components/DepositCrypto/DepositCrypto.pcss
  web/src/components/InputWithButton/index.tsx
  web/src/containers/Wallets/WalletsSpot/WalletsSpot.pcss
  web/src/translations/en.ts
Labels: Ready, QA: Approved

#766 Fix: input style on profile change password modal
  web/src/components/ChangePassword/ChangePassword.pcss
Labels: Ready, QA: Approved

#767 Fix: sign in, sign up style same as figma
  web/src/components/CustomInput/CustomInput.pcss
  web/src/components/SignIn/SignIn.pcss
  web/src/components/SignUp/SignUp.pcss
Labels: QA: Approved, Tech: Approved

#773 Fix: enable 2fa modal style
  web/mocks/api/v2/barong/resource/otp/generate_qrcode/OPTIONS.mock
  web/mocks/api/v2/barong/resource/otp/generate_qrcode/POST.mock
  web/src/screens/ProfileTwoFactorAuthScreen/ProfileTwoFactorAuthScreen.pcss
Labels: Tech: Approved

#769 Fix: internal transfer style
  web/src/components/InternalTransfer/InternalTransfer.pcss
  web/src/components/InternalTransfer/index.tsx
Labels: Tech: Approved

#782 Fix: push trigger_wait orders to state with WS
  web/mocks/ranger.js
  web/src/modules/public/ranger/sagas/rangerSaga.ts
  web/src/modules/user/ordersHistory/helpers.ts
Labels: QA: Approved, Tech: Approved

#781 Fix: push trigger_wait orders to state with WS
  web/mocks/ranger.js
  web/src/modules/public/ranger/sagas/rangerSaga.ts
  web/src/modules/user/ordersHistory/helpers.ts
Labels: QA: Approved, Tech: Approved

#774 Fix: input style on api created modal
  web/src/components/InputWithButton/index.tsx
  web/src/containers/ProfileApiKeys/index.tsx
  web/src/screens/ProfileScreen/ProfileScreen.pcss
Labels: Ready, Tech: Approved

#772 Fix: check fetch wallet on empty list
  web/src/modules/user/wallets/selectors.ts
Labels: Ready, Tech: Approved

#770 Fix: input style on kyc steps
  web/src/components/UploadFile/UploadFile.pcss
  web/src/components/UploadFile/index.tsx
  web/src/containers/Confirm/Address/index.tsx
  web/src/containers/Confirm/Documents/index.tsx
  web/src/custom/translations/ru.ts
  web/src/mobile/styles/screens/ConfirmMobileScreen.pcss
  web/src/screens/ConfirmScreen/ConfirmScreen.pcss
  web/src/translations/en.ts
Labels: Ready, Tech: Approved

#753 Fix: sort history by date
  web/src/containers/Wallets/History.tsx
Labels: Tech: Approved

#763 Feature: otp input for Adding Beneficiary
  web/mocks/api/v2/peatio/account/beneficiaries/GET--currency_id=btc&state[]=active&state[]=pending.mock
  web/mocks/api/v2/peatio/account/beneficiaries/GET--currency_id=dash&state[]=active&state[]=pending.mock
  web/mocks/api/v2/peatio/account/beneficiaries/GET--currency_id=xrp&state[]=active&state[]=pending.mock
  web/mocks/api/v2/peatio/public/config/GET.mock
  web/src/api/index.ts
  web/src/components/Beneficiaries/Beneficiaries.pcss
  web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
  web/src/components/Beneficiaries/index.tsx
  web/src/containers/ModalWithdrawConfirmation/ModalWithdrawConfirmation.pcss
  web/src/containers/Wallets/WalletsSpot/index.tsx
  web/src/containers/Withdraw/index.tsx
  web/src/custom/translations/ru.ts
  web/src/modules/user/beneficiaries/actions.ts
  web/src/modules/user/beneficiaries/sagas/beneficiariesDeleteSaga.ts
  web/src/translations/en.ts
Labels: Tech: Approved

#785 Feature: add hidden status for networks
  web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
  web/src/components/Beneficiaries/BeneficiariesCrypto/BeneficiariesBlockchainItem.tsx
  web/src/components/Beneficiaries/BeneficiariesCrypto/SelectBeneficiariesCrypto.tsx
  web/src/components/Beneficiaries/DropdownBeneficiary.tsx
Labels: Ready, Tech: Approved

#783 Fix: read platform currency config
  web/mocks/api/v2/sonic/public/config/GET.mock
  web/src/api/config.ts
  web/src/api/types.ts
  web/src/components/Beneficiaries/BeneficiariesCrypto/BeneficiariesBlockchainItem.tsx
  web/src/components/Beneficiaries/BeneficiariesCrypto/SelectBeneficiariesCrypto.tsx
  web/src/constants/index.ts
  web/src/containers/Withdraw/UserWithdrawalLimits.tsx
  web/src/containers/Withdraw/index.tsx
Labels: Ready, Tech: Approved

#765 Fix: input style on wallet add whitelist and confirm popup
  web/src/assets/images/PasteIcon.tsx
  web/src/components/Beneficiaries/Beneficiaries.pcss
  web/src/components/Beneficiaries/BeneficiariesActivateModal.tsx
  web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
  web/src/components/CodeVerification/CodeVerification.pcss
  web/src/components/CodeVerification/index.tsx
  web/src/components/CopyableTextField/index.tsx
  web/src/components/CustomInput/CustomInput.pcss
  web/src/components/InputWithButton/index.tsx
  web/src/components/TwoFactorAuth/index.tsx
  web/src/containers/ModalWithdrawConfirmation/ModalWithdrawConfirmation.pcss
  web/src/containers/ModalWithdrawConfirmation/index.tsx
  web/src/containers/TwoFactorAuth/TwoFactorAuth.pcss
  web/src/containers/Wallets/WalletsSpot/WalletsSpot.pcss
  web/src/custom/translations/ru.ts
  web/src/mobile/components/WalletWithdrawBody/index.tsx
  web/src/mobile/styles/components/WalletWithdrawBody.pcss
  web/src/screens/SignInScreen/SignInScreen.pcss
  web/src/translations/en.ts
Labels: Ready

#729 Enhancement: update pkg/jwt version
  go.mod
  go.sum
Labels: Ready

#794 Fix: [trading layout] 996px - 1400px
  web/src/components/LockedComponent/LockedComponent.pcss
  web/src/helpers/layout.ts
  web/src/screens/TradingScreen/index.tsx
Labels: Ready

#790 Feature: Add xlm, eos, luna, xem as memo based currencies
  web/mocks/api/v2/peatio/account/balances/GET.mock
  web/mocks/api/v2/peatio/public/config/GET.mock
  web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
  web/src/constants/index.ts
  web/src/helpers/tagBasedAsset.ts
Labels: WIP

#798 Fix: unit tests
  web/src/components/CodeVerification/CodeVerification.test.tsx
  web/src/components/CodeVerification/__snapshots__/CodeVerification.test.tsx.snap
  web/src/components/CopyableTextField/CopyableTextField.test.tsx
  web/src/components/CopyableTextField/__snapshots__/CopyableTextField.test.tsx.snap
  web/src/components/Decimal/__snapshots__/Decimal.test.tsx.snap
  web/src/components/DepositCrypto/DepositCrypto.test.tsx
  web/src/components/DepositCrypto/__snapshots__/DepositCrypto.test.tsx.snap
  web/src/components/DepositFiat/__snapshots__/DepositFiat.test.tsx.snap
  web/src/components/Markets/__snapshots__/Markets.test.tsx.snap
  web/src/components/Order/__snapshots__/Order.test.tsx.snap
  web/src/components/TwoFactorAuth/__snapshots__/TwoFactorAuth.test.tsx.snap
  web/src/components/WalletItem/WalletItem.test.tsx
  web/src/components/WalletItem/__snapshots__/WalletItem.test.tsx.snap
  web/src/components/WalletList/WalletList.test.tsx
  web/src/components/WalletList/__snapshots__/WalletList.test.tsx.snap
  web/src/constants/constants.test.ts
  web/src/containers/OpenOrders/OpenOrders.test.tsx
  web/src/containers/OpenOrders/__snapshots__/OpenOrders.test.tsx.snap
  web/src/containers/RecentTrades/__snapshots__/RecentTrades.test.tsx.snap
  web/src/containers/WalletsFetch/__snapshots__/WalletsFetch.test.tsx.snap
  web/src/helpers/helpers.test.ts
  web/src/helpers/historyTableUtils.ts
  web/src/modules/admin/config/sagas/configUpdateSaga.test.ts
  web/src/modules/public/alert/sagas/handleErrorAlert.test.ts
  web/src/modules/public/blocklistAccess/reducer.test.ts
  web/src/modules/public/blocklistAccess/sagas/blocklistAccessFetchSaga.test.ts
  web/src/modules/public/orderBook/reducer.test.ts
  web/src/modules/public/orderBook/types.ts
  web/src/modules/public/p2p/actions.test.ts
  web/src/modules/public/p2p/actions.ts
  web/src/modules/public/p2p/reducer.test.ts
  web/src/modules/public/p2p/sagas/p2pPaymentMethodsSaga.test.ts
  web/src/modules/public/p2p/types.ts
  web/src/modules/public/ranger/helpers.test.ts
  web/src/modules/public/ranger/reducer.test.ts
  web/src/modules/public/ranger/sagas/rangerSaga.test.ts
  web/src/modules/public/ranger/sagas/rangerSaga.ts
  web/src/modules/user/abilities/reducer.test.ts
  web/src/modules/user/beneficiaries/actions.test.ts
  web/src/modules/user/beneficiaries/reducer.test.ts
  web/src/modules/user/beneficiaries/sagas/beneficiariesActivateSaga.test.ts
  web/src/modules/user/beneficiaries/sagas/beneficiariesCreateSaga.test.ts
  web/src/modules/user/beneficiaries/sagas/beneficiariesDeleteSaga.test.ts
  web/src/modules/user/beneficiaries/sagas/beneficiariesResendPinSaga.test.ts
  web/src/modules/user/beneficiaries/sagas/beneficiariesSaga.test.ts
  web/src/modules/user/history/sagas/historySaga.test.ts
  web/src/modules/user/kyc/documents/reducer.test.ts
  web/src/modules/user/kyc/documents/sagas/sendDocumentsSaga.test.ts
  web/src/modules/user/openOrders/sagas/userOpenOrdersFetchSaga.test.ts
  web/src/modules/user/p2pOffers/reducer.test.ts
  web/src/modules/user/profile/sagas/userSaga.test.ts
  web/src/modules/user/wallets/reducer.test.ts
  web/src/modules/user/wallets/sagas/walletsSaga.test.ts
  web/src/screens/tests/__snapshots__/ProfileScreen.test.tsx.snap
  web/src/screens/tests/__snapshots__/WalletsScreen.test.tsx.snap
  web/src/store.ts
Labels: Ready

#799 Fix: use platform currency to calculate estimated wallet value
  web/mocks/api/v2/sonic/public/config/GET.mock
  web/src/containers/Wallets/WalletsOverview/index.tsx
  web/src/helpers/estimateValue.ts
Labels: Ready

#802 Fix: fetch p2p currencies on p2p wallet screen
  web/src/containers/Wallets/WalletsP2P/index.tsx
Labels: Ready

#807 Fix: withdraw history under review translation
  web/mocks/api/v2/peatio/account/withdraws/GET--page=1&limit=25.mock
  web/src/containers/HistoryElement/index.tsx
  web/src/custom/translations/ru.ts
  web/src/helpers/historyTableUtils.ts
  web/src/translations/en.ts
Labels: Ready, Tech: Approved

#806 Fix: add quick exchange history translation
  web/src/custom/translations/ru.ts
  web/src/translations/en.ts
Labels: Ready, Tech: Approved

#805 Fix: missing market price change percentage color
  web/src/containers/Markets/index.tsx
Labels: Ready, Tech: Approved

#809 Fix: update go dependencies
  go.mod
  go.sum
Labels: Ready

#810 Fix: expand full trading grit layout
  web/src/helpers/layout.ts
Labels: Ready, Tech: Approved

#811 Feature: Add HBAR as memo based currency
  web/mocks/api/v2/peatio/account/balances/GET.mock
  web/mocks/api/v2/peatio/public/currencies/GET.mock
  web/src/constants/index.ts
Labels: Tech: Approved

#812 Feature: Add HBAR as memo based asset
  web/mocks/api/v2/peatio/account/balances/GET.mock
  web/mocks/api/v2/peatio/public/config/GET.mock
  web/src/constants/index.ts
Labels: Tech: Approved
